  const BLACK_KNIGHTS = [
    {
      id: 'bk1',
      title: 'Shinjuku Ghetto',
      place: 'Shinjuku, Area 11',
      year: '2017 a.t.b.',
      brief:
        'Prince Clovis is razing the Shinjuku Ghetto to recover a stolen secret. A masked student takes over the resistance and the Sutherlands he has commandeered. Break through to the G-1 mobile base.',
      unlock: 'Glasgow and captured Sutherlands',
      player: K,
      sides: [K, B],
      names: { bk: { name: 'Shinjuku Resistance', short: 'Resistance', adj: 'Resistance' } },
      map: SHINJUKU,
      cities: [
        ['Shinjuku Hideout', 2, 6, K, 1],
        ['G-1 Base', 16, 5, B, 2],
      ],
      economy: { bk: 150 },
      hold: { britannia: 3 },
      units: [
        [K, 'glasgow', 3, 5, 1, 'kallen'],
        [K, 'sutherland', 4, 7, 1, 'zero'],
        [K, 'sutherland', 3, 8, 1, 'ohgi'],
        [K, 'sutherland', 5, 4, 1, 'tamaki'],
        [K, 'sutherland', 4, 9, 1, 'inoue'],
        [B, 'sutherland', 10, 3, 2, null, { hold: false }],
        [B, 'sutherland', 11, 7, 1, null, { hold: false }],
        [B, 'glasgow', 9, 5, 1, null, { hold: false }],
        [B, 'glasgow', 12, 9, 2, null, { hold: false }],
        [B, 'sutherland', 14, 4, 1, 'jeremiah'],
        [B, 'gloucester', 15, 6, 2],
        [B, 'sutherland', 15, 4, 1, 'villetta'],
        [B, 'sutherland', 17, 7, 1],
      ],
      objective: 'Capture the G-1 Base. Zero must survive.',
      win: { capture: ['G-1 Base'] },
      lose: { cmd: ['zero'], turns: 15 },
      stars: [{ turns: 10 }, { losses: 1 }],
      victory: 'The G-1 falls. Clovis is alone with Zero, and a rebellion has begun.',
      events: [
        {
          turn: 1,
          say: [
            ['zero', 'You there, in the Glasgow. Do you want to win? Then follow my orders.'],
            ['kallen', 'Who are you? ...Fine. Tell me where to go.'],
            [null, 'Capture the G-1 Base. Your Sutherlands came straight from Britannian pilots, so use them well.'],
          ],
        },
        {
          turn: 5,
          say: [
            ['suzaku', 'Lancelot, launching. Everyone fall back, I will handle this.'],
            ['zero', 'A white Knightmare? That is no ordinary frame. Do not engage it head-on.'],
          ],
          spawn: [[B, 'elite_lancelot', 18, 6, 1, 'suzaku']],
        },
      ],
    },
    {
      id: 'bk2',
      title: 'Lake Kawaguchi',
      place: 'Lake Kawaguchi Convention Center',
      year: '2017 a.t.b.',
      brief:
        'JLF hardliners hold the convention hotel and its hostages; Cornelia’s army rings the lake. Zero’s new Order of the Black Knights strikes both, freeing the hostages in front of the cameras.',
      unlock: 'The Order of the Black Knights is founded',
      player: K,
      sides: [K, 'jlf', B],
      map: [
        'fffppppppppppppppfff',
        'ffpppppppuuppppppfff',
        'fpppppppuuuuppppppff',
        'pppppppppuupppppppff',
        'ppppp..........ppppf',
        'pppp.............ppp',
        'ppp...............pp',
        'pppp..............pp',
        'ffpppp..........pppp',
        'fffppppp......pppppp',
        'ffffppppppppppppppff',
        'fffffppppppppppppfff',
        'ffffffpppppppppfffff',
      ],
      cities: [
        ['Black Knights’ Trailer', 1, 6, K, 1],
        ['Convention Center Hotel', 10, 2, 'jlf', 2],
        ['Britannian Cordon HQ', 11, 11, B, 2],
      ],
      economy: { bk: 200 },
      hold: { jlf: 1, britannia: 2 },
      units: [
        [K, 'burai', 2, 6, 2, 'zero'],
        [K, 'burai', 3, 4, 2, 'kallen'],
        [K, 'burai', 2, 8, 1, 'ohgi'],
        [K, 'burai', 3, 7, 1, 'tamaki'],
        [K, 'burai', 1, 5, 1, 'sugiyama'],
        [K, 'burai', 4, 8, 1, null, { normalOnly: true }],
        ['jlf', 'burai_kai', 10, 3, 2],
        ['jlf', 'burai', 9, 1, 1],
        ['jlf', 'burai', 12, 2, 1, null, { skipNormal: true }],
        ['jlf', 'burai', 11, 3, 1],
        [B, 'sutherland', 7, 10, 2],
        [B, 'gloucester', 11, 10, 1, 'darlton'],
        [B, 'sutherland', 14, 10, 1],
        [B, 'glasgow', 17, 8, 1, null, { hold: false }],
        [B, 'glasgow', 17, 5, 1, null, { hold: false, skipNormal: true }],
        [B, 'sutherland', 18, 3, 2, null, { hold: false, skipNormal: true }],
      ],
      objective: 'Free the hostages: capture the Convention Center Hotel. Zero must survive.',
      win: { capture: ['Convention Center Hotel'] },
      lose: { cmd: ['zero'], turns: 14 },
      stars: [{ destroy: [B] }, { losses: 0 }],
      victory: 'The hostages walk free. Zero introduces the world to the Order of the Black Knights.',
      events: [
        {
          turn: 1,
          say: [
            ['zero', 'Tonight we are neither terrorists nor Britannians. We are allies of justice.'],
            ['ohgi', 'The JLF hold the hotel, and Cornelia has the lake surrounded. We hit both?'],
            ['zero', 'We take the hotel. If Cornelia’s cordon gets in the way, so much the worse for it.'],
          ],
        },
        {
          capture: 'Convention Center Hotel',
          by: K,
          say: [['zero', 'People of the world: we are the Black Knights. We stand with all who are powerless.']],
        },
      ],
    },
    {
      id: 'bk3',
      title: 'Battle of Narita',
      place: 'Mount Narita',
      year: '2017 a.t.b.',
      brief:
        'Cornelia storms the JLF’s mountain fortress. The Black Knights wait on the summit with a new weapon: the Guren Mk-II. A Radiant Wave strike on the slope will bury her army in mud.',
      unlock: 'Guren Mk-II and Kallen',
      player: K,
      sides: [K, 'jlf', B],
      teams: { bk: 'rebels', jlf: 'rebels', britannia: 'empire' },
      map: NARITA,
      cities: [
        ['Narita HQ', 10, 4, 'jlf', 2, { fort: true }],
        ['Britannian Field HQ', 11, 12, B, 2],
      ],
      economy: { bk: 250 },
      hold: { jlf: 2 },
      units: [
        [K, 'burai', 5, 1, 2, 'zero'],
        [K, 'elite_guren_mkii', 6, 2, 1, 'kallen'],
        [K, 'burai', 4, 2, 1, 'ohgi'],
        [K, 'burai', 5, 3, 1, 'tamaki'],
        [K, 'burai', 7, 1, 2, 'minami'],
        [K, 'burai', 8, 2, 1, 'inoue'],
        ['jlf', 'raiko', 10, 4, 1, 'katase'],
        ['jlf', 'burai_kai', 12, 5, 2, 'tohdoh'],
        ['jlf', 'burai_kai', 9, 5, 1, 'chiba'],
        ['jlf', 'burai_kai', 13, 6, 1, 'asahina'],
        ['jlf', 'burai', 11, 6, 1, 'senba'],
        ['jlf', 'burai', 8, 6, 1, 'urabe'],
        [B, 'elite_cornelia_gloucester', 11, 11, 1, 'cornelia', { hold: 3 }],
        [B, 'gloucester', 7, 10, 2, 'darlton'],
        [B, 'gloucester', 15, 10, 2, 'guilford'],
        [B, 'sutherland', 16, 8, 2, 'jeremiah'],
        [B, 'sutherland', 5, 9, 2],
        [B, 'sutherland', 9, 9, 1, 'villetta'],
        [B, 'sutherland', 13, 9, 2],
        [B, 'sutherland', 17, 9, 1],
        [B, 'sutherland', 19, 8, 1],
        [B, 'glasgow', 3, 11, 1],
        [B, 'glasgow', 20, 11, 1],
      ],
      objective: 'Capture the Britannian Field HQ. Zero must survive.',
      win: { capture: ['Britannian Field HQ'] },
      lose: { cmd: ['zero'], turns: 16 },
      stars: [{ kill: ['cornelia'] }, { keep: ['Narita HQ'] }],
      victory: 'Cornelia’s field headquarters is overrun. Narita becomes the Black Knights’ legend.',
      events: [
        {
          turn: 1,
          say: [
            ['zero', 'Kallen, the Guren is ready. On my mark, its Radiant Wave goes into the mountain itself.'],
            ['cornelia', 'Darlton, Guilford: we take Narita today. Crush the JLF to the last frame.'],
          ],
        },
        {
          turn: 3,
          say: [
            ['kallen', 'Radiant Wave Surger... full output!'],
            [null, 'The southern slope gives way. A landslide tears through Cornelia’s lines.'],
          ],
          blast: { c: 10, r: 8, damage: [0.75, 0.6, 0.45], sides: [B], terrain: 'plains', terrainRadius: 2, color: '#b08a5a', name: 'Landslide' },
        },
        {
          turn: 6,
          say: [
            ['suzaku', 'This is the Lancelot. I am going in to rescue the Viceroy.'],
            ['zero', 'That white Knightmare again. Kallen, you are the only one who can stop it.'],
          ],
          spawn: [[B, 'elite_lancelot', 11, 13, 1, 'suzaku']],
        },
      ],
    },
    {
      id: 'bk4',
      title: 'The Black Rebellion',
      place: 'Tokyo Settlement',
      year: '2017 a.t.b.',
      brief:
        'Japan rises. The Black Knights pour into the Tokyo Settlement from Ashford Academy. Take the city’s districts and the Government Bureau before Britannian reinforcements land from the bay.',
      unlock: 'Gawain and Zero',
      player: K,
      sides: [K, B],
      map: TOKYO,
      cities: [
        ['Ashford Academy', 3, 7, K, 2],
        ['Settlement Gate', 8, 3, B, 1],
        ['Tokyo Tower', 12, 10, B, 2],
        ['Government Bureau', 18, 6, B, 3, { fort: true, gun: 'Government Bureau' }],
      ],
      economy: { bk: 400, britannia: 0 },
      industry: { bk: 120 },
      buildable: R1_BUILD,
      hold: { britannia: 3 },
      units: [
        [K, 'elite_gawain', 4, 6, 1, 'zero'],
        [K, 'elite_guren_mkii', 5, 8, 1, 'kallen'],
        [K, 'elite_tohdoh_gekka', 5, 5, 1, 'tohdoh'],
        [K, 'gekka', 4, 9, 1, 'chiba'],
        [K, 'gekka', 6, 7, 1, 'asahina'],
        [K, 'burai', 3, 9, 2, 'ohgi'],
        [K, 'burai', 3, 5, 1, 'tamaki'],
        [K, 'gekka', 6, 4, 1, 'urabe'],
        [K, 'gekka', 6, 10, 1, 'senba'],
        [K, 'burai', 7, 8, 2, 'inoue'],
        [K, 'gekka', 7, 6, 1, null, { normalOnly: true }],
        [B, 'elite_cornelia_gloucester', 17, 7, 1, 'cornelia'],
        [B, 'gloucester', 16, 5, 2, 'guilford'],
        [B, 'gloucester', 13, 8, 2, 'darlton', { hold: false }],
        [B, 'sutherland', 9, 4, 2, null, { hold: 2 }],
        [B, 'sutherland', 10, 7, 1, null, { hold: false }],
        [B, 'sutherland', 11, 11, 2, null, { hold: 2 }],
        [B, 'sutherland', 14, 3, 1],
        [B, 'sutherland', 15, 9, 2],
        [B, 'sutherland', 19, 4, 1],
        [B, 'glasgow', 8, 9, 1, null, { hold: false }],
        [B, 'glasgow', 12, 5, 1, null, { hold: false }],
      ],
      objective: 'Capture the Government Bureau. Zero must survive.',
      win: { capture: ['Government Bureau'] },
      lose: { cmd: ['zero'], turns: 16 },
      stars: [{ turns: 9 }, { capture: ['Settlement Gate', 'Tokyo Tower', 'Government Bureau'] }],
      victory: 'The Government Bureau falls. For one night, Tokyo belongs to Japan.',
      events: [
        {
          turn: 1,
          say: [
            ['zero', 'Black Knights! The Settlement is ours to take. Strike now, before the fleet arrives.'],
            ['tohdoh', 'The Four Holy Swords will open the road. Follow the Gekka.'],
          ],
        },
        {
          turn: 4,
          say: [['cornelia', 'Reinforcements from the bay are landing. Hold the Bureau at all costs!']],
          spawn: [
            [B, 'sutherland', 21, 2, 2, null, { hold: false }],
            [B, 'sutherland', 21, 6, 1, null, { hold: false, skipNormal: true }],
            [B, 'sutherland', 21, 10, 2, null, { hold: false }],
          ],
        },
        {
          turn: 6,
          say: [['suzaku', 'Lancelot, entering the Settlement. I will not let Zero win this.']],
          spawn: [[B, 'elite_lancelot', 21, 7, 1, 'suzaku']],
        },
        {
          turn: 8,
          say: [[null, 'A second wave of Britannian frames comes ashore.']],
          spawn: [
            [B, 'gloucester', 21, 4, 2, null, { hold: false }],
            [B, 'gloucester', 21, 9, 2, null, { hold: false, skipNormal: true }],
          ],
        },
      ],
    },
    {
      id: 'bk5',
      title: 'Battle of Babel Tower',
      place: 'Babel Tower, Tokyo Settlement',
      year: '2018 a.t.b.',
      brief:
        'A year after the failed Black Rebellion, Lelouch is drawn into Babel Tower and regains his memories as Zero. Break out of the tower with Kallen and C.C. and reach the Chinese Consulate before Area 11 can seal the district.',
      unlock: 'Zero returns',
      player: K,
      sides: [K, 'cf', B],
      teams: { bk: 'rebels', cf: 'rebels', britannia: 'empire' },
      names: { cf: { name: 'Chinese Consulate', short: 'Consulate', adj: 'Consulate' } },
      map: [
        '..uuuuuuuuuuuuuuuuuu',
        '..uuuxuuuuuuuxuuuuuu',
        '.puuuuuuuuuuuuuuuuup',
        '.puuuuuuxuuuuuuuuupp',
        'ppuuuuuuuuuuuxuuuupp',
        'ppuuuxuuuuuuuuuuuupp',
        'ppuuuuuuuuuuuuuuuupp',
        '.puuuuuuuuxuuuuuuupp',
        '.puuuuuuuuuuuuuxuuup',
        '..uuuxuuuuuuuuuuuuuu',
        '..uuuuuuuuuuxuuuuuuu',
        '...uuuuuuuuuuuuuuuuu',
      ],
      cities: [
        ['Babel Tower', 3, 6, K, 1],
        ['OSI Blockade', 11, 4, B, 1],
        ['Chinese Consulate', 18, 6, 'cf', 1],
      ],
      economy: { bk: 180 },
      hold: { cf: 1 },
      units: [
        [K, 'burai', 3, 5, 2, 'zero'],
        [K, 'burai', 4, 7, 1, 'cc'],
        [K, 'burai_kai', 4, 5, 1, 'kallen'],
        [K, 'burai', 5, 7, 1, null, { normalOnly: true }],
        [B, 'vincent_commander', 9, 6, 1, 'rolo'],
        [B, 'sutherland', 8, 4, 1],
        [B, 'sutherland', 10, 5, 2],
        [B, 'sutherland', 12, 7, 1],
        [B, 'sutherland', 14, 4, 1, null, { skipNormal: true }],
        [B, 'gloucester', 15, 8, 1, null, { skipNormal: true }],
        ['cf', 'gun_ru', 18, 7, 2],
      ],
      objective: 'Reach the Chinese Consulate. Zero must survive.',
      win: { reach: ['Chinese Consulate'] },
      lose: { cmd: ['zero'], turns: 11 },
      stars: [{ capture: ['OSI Blockade'] }, { alive: ['kallen', 'cc'] }],
      victory: 'Zero escapes Babel Tower and reaches Chinese territory. The Black Knights have their leader again.',
      events: [
        {
          turn: 1,
          say: [
            ['zero', 'I remember now. I am Zero. Kallen, C.C.—we leave Babel Tower and reach the consulate.'],
            ['kallen', 'Welcome back, Zero.'],
          ],
        },
        {
          turn: 4,
          say: [['rolo', 'You are not getting out of the Settlement.']],
          spawn: [[B, 'sutherland', 16, 5, 1]],
        },
      ],
    },
    {
      id: 'bk6',
      title: 'Mausoleum of the Eighty-Eight Emperors',
      place: 'Luoyang, Chinese Federation',
      year: '2018 a.t.b.',
      brief:
        'Besieged at the Mausoleum of the Eighty-Eight Emperors, Zero unveils the Shinkirō and exposes the High Eunuchs’ bargain with Britannia. Li Xingke turns on the Eunuchs, and the Black Knights march with him on the Vermillion Forbidden City.',
      unlock: 'Shinkirō, Federation frames and Shen Hu support',
      player: K,
      sides: [K, 'cf', 'neutral', B],
      teams: { bk: 'rebels', cf: 'rebels', neutral: 'empire', britannia: 'empire' },
      names: EUNUCH_NAMES,
      map: LUOYANG,
      cities: LUOYANG_CITIES,
      economy: { bk: 400 },
      industry: { bk: 150 },
      production: [],
      hold: { neutral: 3 },
      units: [...LUOYANG_REBELS, ...LUOYANG_EUNUCHS],
      objective: 'Capture the Vermillion Forbidden City. Zero must survive.',
      win: { capture: ['Vermillion Forbidden City'] },
      lose: { cmd: ['zero'], turns: 18 },
      stars: [{ alive: ['xingke'] }, { turns: 11 }],
      victory: 'The High Eunuchs fall. The Tianzi is free, and the Federation turns toward the Black Knights.',
      events: [
        {
          turn: 1,
          say: [
            ['zero', 'The Eunuchs have sold the Tianzi to Britannia, and now all of China has heard it. Shinkirō, advance!'],
            ['xingke', 'Zero. For the Tianzi’s sake, I will fight beside you, this once.'],
            ['zero', 'Then let us end the Eunuchs’ rule together. The Forbidden City, Xingke.'],
          ],
        },
        {
          turn: 4,
          say: [
            ['schneizel', 'The Eunuchs asked for our help. Let us not keep them waiting.'],
            ['zero', 'Schneizel’s Vincents. So Britannia has shown its hand.'],
          ],
          spawn: [
            [B, 'vincent_ward', 21, 5, 2],
            [B, 'vincent_ward', 21, 8, 2],
            [B, 'sutherland', 21, 3, 2],
            [B, 'sutherland', 21, 10, 1],
          ],
        },
        {
          turn: 7,
          say: [['guilford', 'For Princess Cornelia’s honor: Zero falls today.']],
          spawn: [[B, 'gloucester', 21, 6, 2, 'guilford']],
        },
      ],
    },
    {
      id: 'bk7',
      title: 'Second Battle of Tokyo',
      place: 'Tokyo Settlement',
      year: '2018 a.t.b.',
      brief:
        'The Black Knights return to Tokyo with Gefjun Disturbers. Each one switched on shuts down the Knightmares around the Government Bureau. Britannia has a weapon of its own: F.L.E.I.J.A.',
      unlock: 'Gefjun Disturber',
      player: K,
      sides: [K, B],
      map: TOKYO,
      cities: [
        ['Ikaruga Landing', 2, 7, K, 2],
        ['Gefjun Point North', 9, 2, B, 1],
        ['Gefjun Point West', 7, 10, B, 1],
        ['Gefjun Point South', 13, 12, B, 1],
        ['Ashford Academy', 13, 6, B, 1],
        ['Government Bureau', 18, 6, B, 3, { fort: true, gun: 'Government Bureau' }],
      ],
      economy: { bk: 500 },
      industry: { bk: 200 },
      hold: { britannia: 2 },
      units: [
        [K, 'elite_shinkiro', 3, 6, 1, 'zero'],
        [K, 'elite_guren_mkii', 4, 8, 1, 'kallen'],
        [K, 'zangetsu', 4, 5, 1, 'tohdoh'],
        [K, 'akatsuki_zikisan', 5, 7, 1, 'chiba'],
        [K, 'akatsuki_zikisan', 3, 9, 1, 'asahina'],
        [K, 'akatsuki', 5, 4, 2, 'ohgi'],
        [K, 'akatsuki', 6, 6, 2, 'sugiyama'],
        [K, 'akatsuki', 5, 10, 2, 'minami'],
        [K, 'akatsuki', 6, 8, 2, 'senba'],
        [K, 'akatsuki_missile', 2, 5, 1],
        [B, 'elite_lancelot', 17, 7, 1, 'suzaku', { hold: false }],
        [B, 'brighton', 16, 4, 1, 'gino', { hold: false }],
        [B, 'elite_mordred', 19, 8, 1, 'anya'],
        [B, 'vincent_commander', 15, 9, 2, 'guilford'],
        [B, 'vincent_ward', 10, 4, 2, null, { hold: false }],
        [B, 'vincent_ward', 11, 8, 2, null, { hold: false }],
        [B, 'vincent_ward', 13, 10, 2],
        [B, 'vincent_ward', 14, 5, 2],
        [B, 'sutherland', 9, 2, 1, null, { hold: 1 }],
        [B, 'sutherland', 7, 10, 1, null, { hold: 1 }],
        [B, 'sutherland', 13, 12, 1, null, { hold: 1 }],
        [B, 'gareth', 19, 5, 1],
      ],
      objective: 'Capture the Government Bureau. Gefjun Points shut down nearby defenders. Zero must survive.',
      win: { capture: ['Government Bureau'] },
      lose: { cmd: ['zero'], turns: 18 },
      stars: [{ capture: ['Gefjun Point North', 'Gefjun Point West', 'Gefjun Point South'] }, { losses: 3 }],
      victory: 'The Bureau falls amid the ruins F.L.E.I.J.A. left behind. Tokyo will never be the same.',
      events: [
        {
          turn: 1,
          say: [
            ['zero', 'Take the Gefjun Points. Every Disturber we light blinds the frames around the Bureau.'],
            ['suzaku', 'Zero is here again. This time I end it, whatever it takes.'],
          ],
        },
        ...['North', 'West', 'South'].map(p => ({
          capture: `Gefjun Point ${p}`,
          by: K,
          say: [[null, `Gefjun Disturber ${p} is online. Britannian frames near the Bureau seize up.`]],
          stun: { c: 17, r: 6, radius: 3, sides: [B], name: 'Gefjun Disturber' },
          shield: { city: 'Government Bureau', value: 120 },
        })),
        {
          turn: 5,
          say: [
            ['kallen', 'Rakshata’s package... the Guren S.E.I.T.E.N.? Then let’s go!'],
            [null, 'Kallen’s Guren is refitted with Energy Wings.'],
          ],
          upgrade: { cmd: 'kallen', type: 'elite_guren_seiten' },
        },
        {
          turn: 6,
          say: [
            ['suzaku', 'The F.L.E.I.J.A. warhead is armed. Target: the city center.'],
            [null, 'Warning: strategic weapon detected. Clear the marked area.'],
          ],
          warn: { c: 12, r: 7, radius: 2, label: 'F.L.E.I.J.A.' },
        },
        {
          turn: 7,
          say: [
            [null, 'F.L.E.I.J.A. detonation. Everything inside the sphere is erased.'],
            ['zero', 'Tokyo... Suzaku, what have you done?'],
          ],
          blast: { c: 12, r: 7, damage: [1, 1, 0.6], terrain: 'crater', terrainRadius: 1, color: '#ffc4ec', name: 'F.L.E.I.J.A.' },
        },
      ],
    },
    {
      id: 'bk9',
      title: 'Battle of Mount Fuji',
      place: 'Mount Fuji',
      year: '2018 a.t.b.',
      brief:
        'Emperor Lelouch’s Britannia meets the Black Knights and the UFN beneath Mount Fuji, above the world’s richest Sakuradite mines. When the mines erupt, nothing on the slopes is safe.',
      unlock: 'Elite Black Knight frames',
      player: K,
      sides: [K, 'cf', B],
      teams: { bk: 'ufn', cf: 'ufn', britannia: 'empire' },
      names: { cf: { name: 'UFN Federation Army', short: 'UFN', adj: 'UFN' } },
      map: FUJI,
      cities: [
        ['Ikaruga', 2, 6, K, 2],
        ['Fuji Mine West', 6, 4, B, 1],
        ['Fuji Mine East', 15, 8, B, 1],
        ['Avalon Landing', 19, 5, B, 3, { fort: true, gun: 'Avalon' }],
      ],
      economy: { bk: 500 },
      industry: { bk: 200 },
      hold: { britannia: 3 },
      units: [
        [K, 'elite_guren_seiten', 3, 5, 1, 'kallen'],
        [K, 'zangetsu', 3, 7, 1, 'tohdoh'],
        [K, 'akatsuki_zikisan', 4, 4, 1, 'chiba'],
        [K, 'akatsuki_zikisan', 4, 8, 1, 'asahina'],
        [K, 'akatsuki', 2, 8, 2, 'ohgi'],
        [K, 'akatsuki', 5, 6, 2],
        [K, 'akatsuki_flight', 3, 3, 2],
        [K, 'akatsuki_missile', 2, 4, 1],
        [K, 'brighton', 4, 9, 1, 'gino'],
        ['cf', 'shen_hu', 3, 10, 1, 'xingke'],
        ['cf', 'gun_ru', 4, 11, 2, 'xianglin'],
        ['cf', 'gun_ru', 5, 10, 2],
        ['cf', 'chuyen', 2, 11, 1],
        [B, 'elite_shinkiro', 19, 5, 1, 'lelouch', { hold: 1 }],
        [B, 'elite_lancelot_albion', 16, 6, 1, 'suzaku', { hold: false }],
        [B, 'vincent_commander', 17, 9, 2, 'jeremiah', { hold: false }],
        [B, 'vincent_ward', 15, 3, 2],
        [B, 'vincent_ward', 14, 9, 2],
        [B, 'vincent_ward', 17, 2, 2],
        [B, 'vincent_ward', 18, 8, 2],
        [B, 'gareth', 18, 4, 1],
        [B, 'gareth', 19, 7, 1],
        [B, 'sutherland', 6, 4, 1, null, { hold: 1 }],
        [B, 'sutherland', 15, 8, 1, null, { hold: 1 }],
      ],
      objective: 'Capture Avalon Landing. Beware the Sakuradite mines beneath Fuji.',
      win: { capture: ['Avalon Landing'] },
      lose: { cities: ['Ikaruga'], turns: 18 },
      stars: [{ kill: ['suzaku'] }, { alive: ['kallen', 'tohdoh'] }],
      victory: 'Avalon’s landing field is taken. The Emperor’s army falls back from Fuji.',
      events: [
        {
          turn: 1,
          say: [
            ['tohdoh', 'Lelouch commands Britannia now. We fight for what Zero once promised.'],
            ['kallen', 'Then I will stop Suzaku myself.'],
          ],
        },
        {
          turn: 3,
          say: [[null, 'Seismic alarms: the Sakuradite seams under the summit are about to rupture.']],
          warn: { c: 11, r: 5, radius: 2, label: 'Eruption' },
        },
        {
          turn: 4,
          say: [[null, 'The summit mine erupts. Fuji’s crown collapses in a pink Sakuradite fire.']],
          blast: { c: 11, r: 5, damage: [1, 0.8, 0.5], terrain: 'crater', terrainRadius: 1, color: '#ff9ad5', name: 'Sakuradite eruption' },
        },
        {
          turn: 6,
          say: [[null, 'A second seam is giving way on the western slope.']],
          warn: { c: 8, r: 8, radius: 1, label: 'Eruption' },
        },
        {
          turn: 7,
          say: [[null, 'The western mine bursts, scattering every frame nearby.']],
          blast: { c: 8, r: 8, damage: [1, 0.7], terrain: 'crater', color: '#ff9ad5', name: 'Sakuradite eruption' },
        },
      ],
    },
    {
      id: 'bk10',
      title: 'The Final Battle',
      place: 'Skies over Mount Fuji',
      year: '2018 a.t.b.',
      brief:
        'Schneizel’s Damocles hangs over the battlefield, firing F.L.E.I.J.A. at Lelouch’s army. Fight beneath it, defend the fortress, and bring down the Emperor himself.',
      unlock: 'Campaign complete',
      player: K,
      sides: [K, 'cf', 'neutral', B],
      teams: { bk: 'ufn', cf: 'ufn', neutral: 'ufn', britannia: 'empire' },
      names: {
        cf: { name: 'UFN Federation Army', short: 'UFN', adj: 'UFN' },
        neutral: { name: 'Damocles', short: 'Damocles', adj: 'Damocles', color: '#c8d4e8' },
      },
      map: SKY,
      cities: [
        ['Damocles', 12, 1, 'neutral', 3, { fort: true, gun: 'Damocles', shield: 900 }],
        ['Ikaruga', 3, 4, K, 2],
        ['Fuji Mine', 6, 8, B, 1],
        ['Shizuoka', 18, 8, B, 1],
        ['Avalon', 12, 12, B, 3, { fort: true, gun: 'Avalon' }],
      ],
      economy: { bk: 600 },
      industry: { bk: 250 },
      hold: { neutral: 1 },
      units: [
        [K, 'elite_guren_seiten', 5, 4, 1, 'kallen'],
        [K, 'zangetsu', 4, 6, 1, 'tohdoh'],
        [K, 'akatsuki_zikisan', 6, 3, 1, 'chiba'],
        [K, 'akatsuki_zikisan', 6, 6, 1, 'asahina'],
        [K, 'akatsuki', 3, 6, 2, 'ohgi'],
        [K, 'akatsuki', 7, 5, 2],
        [K, 'akatsuki', 5, 7, 2],
        [K, 'akatsuki_flight', 8, 3, 2],
        [K, 'akatsuki_flight', 8, 6, 2],
        [K, 'akatsuki_missile', 3, 3, 1],
        ['cf', 'shen_hu', 18, 3, 1, 'xingke'],
        ['cf', 'gun_ru', 19, 2, 2],
        ['cf', 'chuyen', 17, 4, 1],
        ['neutral', 'gareth', 12, 1, 1, 'schneizel'],
        ['neutral', 'brighton', 11, 2, 1],
        [B, 'elite_shinkiro', 12, 12, 1, 'lelouch', { hold: 1 }],
        [B, 'elite_lancelot_albion', 11, 10, 1, 'suzaku'],
        [B, 'vincent_commander', 14, 10, 2, 'jeremiah'],
        [B, 'vincent_ward', 8, 11, 2],
        [B, 'vincent_ward', 10, 9, 2],
        [B, 'vincent_ward', 15, 9, 2],
        [B, 'vincent_ward', 17, 11, 2],
        [B, 'vincent_ward', 6, 9, 2],
        [B, 'gareth', 11, 12, 1, null, { hold: 2 }],
        [B, 'gareth', 13, 11, 1, null, { hold: 2 }],
        [B, 'gareth', 18, 8, 1],
        [B, 'sutherland', 6, 8, 1, null, { hold: 1 }],
      ],
      objective: 'Destroy Emperor Lelouch’s unit. Damocles must not fall.',
      win: { kill: ['lelouch'] },
      lose: { cities: ['Damocles'], turns: 20 },
      stars: [{ kill: ['suzaku'] }, { turns: 14 }],
      victory: 'The Emperor’s frame falls from the sky. The war for the world is over.',
      events: [
        {
          turn: 1,
          say: [
            ['schneizel', 'Damocles will keep the world in check. Black Knights, the Emperor is yours.'],
            ['kallen', 'Lelouch... I will reach you, whatever it costs.'],
          ],
        },
        {
          turn: 2,
          say: [[null, 'Damocles is locking a F.L.E.I.J.A. onto the center of the field.']],
          warn: { c: 12, r: 8, radius: 2, label: 'F.L.E.I.J.A.' },
        },
        {
          turn: 3,
          say: [[null, 'F.L.E.I.J.A. impact. The center of the battlefield is erased.']],
          blast: { c: 12, r: 8, damage: [1, 1, 0.6], terrain: 'crater', color: '#ffc4ec', name: 'F.L.E.I.J.A.' },
        },
        {
          turn: 4,
          say: [['lelouch', 'All units, push on. Damocles must be taken.']],
          spawn: [
            [B, 'vincent_ward', 12, 13, 2],
            [B, 'gareth', 9, 13, 1],
          ],
        },
        {
          turn: 5,
          say: [[null, 'Damocles retargets the western flank.']],
          warn: { c: 8, r: 10, radius: 2, label: 'F.L.E.I.J.A.' },
        },
        {
          turn: 6,
          blast: { c: 8, r: 10, damage: [1, 1, 0.6], terrain: 'crater', color: '#ffc4ec', name: 'F.L.E.I.J.A.' },
          say: [[null, 'A second F.L.E.I.J.A. sphere blooms over the western flank.']],
        },
        {
          turn: 8,
          say: [[null, 'Damocles retargets the eastern flank.']],
          warn: { c: 16, r: 10, radius: 2, label: 'F.L.E.I.J.A.' },
        },
        {
          turn: 9,
          blast: { c: 16, r: 10, damage: [1, 1, 0.6], terrain: 'crater', color: '#ffc4ec', name: 'F.L.E.I.J.A.' },
          say: [[null, 'The eastern flank vanishes in light.']],
        },
      ],
    },
  ];

