  const BRITANNIA = [
    {
      id: 'br1',
      title: 'Invasion of Japan',
      place: 'Kantō Plain',
      year: '2010 a.t.b.',
      brief:
        'August 10, 2010. Britannia invades Japan for its Sakuradite. Lead the Glasgow, the first Knightmare ever to see battle, against tanks and artillery, and take Tokyo.',
      unlock: 'Glasgow and Sutherland',
      player: B,
      sides: [B, 'jlf'],
      names: { jlf: { name: 'Japanese Military', short: 'Japan', adj: 'Japanese', color: '#e46a5a' } },
      map: [
        'fffmmmpppppppppppp....',
        'ffmmmpppppfffppppp....',
        'fffmppppuuppfffpppp...',
        'ffmmpppuuuuppfffppp...',
        'fmmppppuuuppppppppp...',
        'ffmpppppuppppfffppp...',
        'fffpppppppppffffpppp..',
        'ffmmppfffppppppppppp..',
        'fmmpppfffppppmmppppp..',
        'ffmmppppppppmmmpppp...',
        'fffmpppppppppmppppp...',
        'ffffmmpppppppppppp....',
        'fffffmmpppppppppp.....',
      ],
      cities: [
        ['Landing Zone', 18, 6, B, 1],
        ['Yokohama', 9, 8, 'jlf', 2],
        ['Tokyo', 8, 3, 'jlf', 3, { fort: true, gun: 'Tokyo defenses' }],
      ],
      economy: { britannia: 300 },
      industry: { britannia: 80 },
      buildable: { britannia: ['glasgow'] },
      hold: { jlf: 3 },
      units: [
        [B, 'glasgow', 17, 5, 2, 'darlton'],
        [B, 'glasgow', 17, 7, 2, 'jeremiah'],
        [B, 'glasgow', 18, 4, 2],
        [B, 'glasgow', 16, 6, 1],
        [B, 'glasgow', 18, 8, 2],
        [B, 'glasgow', 16, 3, 1],
        [B, 'glasgow', 16, 9, 1],
        [B, 'glasgow', 15, 5, 1, null, { normalOnly: true }],
        [B, 'glasgow', 15, 8, 1, null, { normalOnly: true }],
        ['jlf', 'jp_tank', 11, 5, 3, 'tohdoh', { hold: false }],
        ['jlf', 'jp_tank', 12, 3, 2, null, { hold: false }],
        ['jlf', 'jp_tank', 13, 6, 1, null, { hold: false, skipNormal: true }],
        ['jlf', 'jp_tank', 12, 8, 2],
        ['jlf', 'jp_tank', 9, 5, 2],
        ['jlf', 'jp_tank', 10, 2, 1],
        ['jlf', 'jp_tank', 8, 3, 2, null, { hold: 1 }],
        ['jlf', 'jp_artillery', 9, 4, 1],
        ['jlf', 'jp_artillery', 8, 6, 1],
        ['jlf', 'jp_artillery', 10, 9, 1, null, { skipNormal: true }],
      ],
      objective: 'Capture Tokyo.',
      win: { capture: ['Tokyo'] },
      lose: { turns: 16 },
      stars: [{ turns: 10 }, { kill: ['tohdoh'] }],
      victory: 'Tokyo falls within a month. Japan becomes Area 11, and the Knightmare era begins.',
      events: [
        {
          turn: 1,
          say: [
            ['darlton', 'Glasgows, advance! Their tanks have never faced a Knightmare. Show them why.'],
            [null, 'The Glasgow is cheap and fast. Build more at the Landing Zone and capture Tokyo.'],
          ],
        },
        {
          turn: 4,
          say: [['tohdoh', 'Strike their flank from the hills. Japan will not fall without a fight.']],
          spawn: [
            ['jlf', 'jp_tank', 1, 6, 2, null, { hold: false }],
            ['jlf', 'jp_tank', 1, 8, 2, null, { hold: false }],
          ],
        },
      ],
    },
    {
      id: 'br2',
      title: 'Shinjuku Suppression',
      place: 'Shinjuku, Area 11',
      year: '2017 a.t.b.',
      brief:
        'Clovis orders the Shinjuku Ghetto cleared. The terrorists should be easy prey for the Purist Faction’s Sutherlands, until someone starts giving them orders.',
      unlock: 'Jeremiah Gottwald',
      player: B,
      sides: [B, K],
      names: { bk: { name: 'Shinjuku Resistance', short: 'Resistance', adj: 'Resistance' } },
      map: SHINJUKU,
      cities: [
        ['Resistance Hideout', 2, 6, K, 1],
        ['G-1 Base', 16, 5, B, 2],
      ],
      economy: { britannia: 200 },
      units: [
        [B, 'sutherland', 15, 4, 2, 'jeremiah'],
        [B, 'sutherland', 14, 6, 2, 'villetta'],
        [B, 'sutherland', 13, 3, 1],
        [B, 'sutherland', 16, 7, 1],
        [B, 'sutherland', 12, 8, 2],
        [B, 'glasgow', 13, 10, 1],
        [B, 'glasgow', 12, 1, 1],
        [K, 'glasgow', 4, 5, 1, 'kallen'],
        [K, 'glasgow', 6, 8, 1, 'inoue'],
        [K, 'glasgow', 5, 3, 1, 'sugiyama'],
      ],
      objective: 'Wipe out the resistance. The G-1 Base must not fall.',
      win: [{ destroy: [K] }, { turn: 4 }],
      lose: { cities: ['G-1 Base'], turns: 14 },
      stars: [{ alive: ['jeremiah'] }, { losses: 2 }],
      victory: 'Shinjuku is silent. Whoever was commanding the terrorists has vanished.',
      events: [
        {
          turn: 1,
          say: [['jeremiah', 'Purist Faction, sweep the ghetto. Leave nothing standing that can hold a rifle.'],
            ['villetta', 'Understood, Lord Jeremiah. My squad takes the east side.'],
          ],
        },
        {
          turn: 3,
          say: [
            ['zero', 'Take these Sutherlands. Follow my instructions exactly and you will win.'],
            ['jeremiah', 'Our own Sutherlands are firing on us? Who is commanding them?'],
          ],
          spawn: [
            [K, 'sutherland', 7, 6, 1, 'zero'],
            [K, 'sutherland', 8, 4, 1, 'tamaki'],
            [K, 'sutherland', 8, 9, 1, 'ohgi'],
            [K, 'sutherland', 6, 2, 1, 'minami'],
          ],
        },
      ],
    },
    {
      id: 'br3',
      title: 'Saitama',
      place: 'Saitama Ghetto',
      year: '2017 a.t.b.',
      brief:
        'Cornelia stages a copy of Clovis’s Shinjuku operation in Saitama, as bait. The Yamato Alliance hides in the ruins. If Zero takes the bait, he walks into her trap.',
      unlock: 'Gloucester and Cornelia',
      player: B,
      sides: [B, 'jlf', K],
      names: { jlf: { name: 'Yamato Alliance', short: 'Yamato', adj: 'Yamato' } },
      map: [
        'ppppppppppppppppppff',
        'pppppuuuuuuuuppppppf',
        'ppppuuuxuuuuuuuppppp',
        'pppuuuuuuuxuuuuupppp',
        'pppuuxuuuuuuuuuupppp',
        'ppuuuuuuuuuuuxuuuppp',
        'pppuuuuxuuuuuuuupppp',
        'pppuuuuuuuuuxuuupppp',
        'ppppuuuuuuuuuuuppppp',
        'fpppppuuuuuuuppppppp',
        'ffpppppppppppppppppp',
        'fffppppppppppppppppp',
      ],
      cities: [
        ['Saitama Ghetto', 8, 5, 'jlf', 1],
        ['G-1 Command', 16, 10, B, 2],
      ],
      economy: { britannia: 200 },
      hold: { jlf: 3 },
      units: [
        [B, 'elite_cornelia_gloucester', 15, 9, 1, 'cornelia'],
        [B, 'gloucester', 13, 10, 2, 'darlton'],
        [B, 'sutherland', 3, 10, 2, 'villetta'],
        [B, 'sutherland', 18, 5, 2],
        [B, 'sutherland', 10, 11, 1],
        [B, 'sutherland', 4, 1, 1],
        [B, 'sutherland', 15, 2, 2],
        [B, 'glasgow', 1, 5, 1],
        [B, 'glasgow', 18, 1, 1],
        ['jlf', 'burai', 8, 5, 2],
        ['jlf', 'burai', 6, 3, 1],
        ['jlf', 'burai', 11, 4, 2],
        ['jlf', 'burai', 7, 7, 1],
        ['jlf', 'burai', 12, 7, 1],
      ],
      objective: 'Destroy the Yamato Alliance and anyone who comes to help them. Cornelia must survive.',
      win: [{ destroy: ['jlf', K] }, { turn: 4 }],
      lose: { cmd: ['cornelia'], cities: ['G-1 Command'], turns: 15 },
      stars: [{ kill: ['zero'] }, { losses: 2 }],
      victory: 'The ghetto is cleared. Zero slipped the net, but he will not underestimate Cornelia again.',
      events: [
        {
          turn: 1,
          say: [
            ['cornelia', 'This operation is bait. If Zero is who I think he is, he will come.'],
            ['darlton', 'The cordon is in place, Your Highness. Nothing leaves Saitama.'],
          ],
        },
        {
          turn: 3,
          say: [
            ['zero', 'A trap, Cornelia? Then I will spring it from the inside.'],
            ['cornelia', 'There you are. All units, close in on Zero!'],
          ],
          spawn: [
            [K, 'sutherland', 9, 6, 1, 'zero'],
            [K, 'sutherland', 7, 4, 1],
            [K, 'sutherland', 10, 7, 1],
          ],
        },
      ],
    },
    {
      id: 'br4',
      title: 'Assault on Narita',
      place: 'Mount Narita',
      year: '2017 a.t.b.',
      brief:
        'The JLF’s mountain fortress must fall. Cornelia surrounds Narita, but something waits on the summit: the Black Knights, and a red Knightmare that can bring the mountain down.',
      unlock: 'Elite Britannian frames',
      player: B,
      sides: [B, 'jlf', K],
      map: NARITA,
      cities: [
        ['Narita HQ', 10, 4, 'jlf', 2, { fort: true, gun: 'Narita' }],
        ['Britannian Field HQ', 11, 12, B, 2],
      ],
      economy: { britannia: 300 },
      hold: { jlf: 2 },
      units: [
        [B, 'elite_cornelia_gloucester', 11, 11, 1, 'cornelia'],
        [B, 'gloucester', 7, 10, 2, 'darlton'],
        [B, 'gloucester', 15, 10, 2, 'guilford'],
        [B, 'sutherland', 16, 8, 2, 'jeremiah'],
        [B, 'sutherland', 5, 9, 2],
        [B, 'sutherland', 9, 9, 2, 'villetta'],
        [B, 'sutherland', 13, 9, 2],
        [B, 'sutherland', 17, 9, 1],
        [B, 'sutherland', 19, 8, 1],
        [B, 'glasgow', 3, 11, 1],
        [B, 'glasgow', 20, 11, 1],
        ['jlf', 'raiko', 10, 4, 1, 'katase'],
        ['jlf', 'burai_kai', 12, 5, 2, 'tohdoh', { hold: 3 }],
        ['jlf', 'burai_kai', 9, 5, 1, 'chiba'],
        ['jlf', 'burai_kai', 13, 6, 1, 'asahina'],
        ['jlf', 'burai', 11, 6, 2, 'senba'],
        ['jlf', 'burai', 8, 6, 2, 'urabe'],
        ['jlf', 'burai', 14, 4, 1],
        ['jlf', 'raiko', 7, 4, 1],
      ],
      objective: 'Capture Narita HQ. Cornelia must survive.',
      win: { capture: ['Narita HQ'] },
      lose: { cmd: ['cornelia'], turns: 18 },
      stars: [{ kill: ['katase'] }, { kill: ['kallen'] }],
      victory: 'Narita HQ falls. The JLF is broken, and Cornelia has met the red Knightmare.',
      events: [
        {
          turn: 1,
          say: [['cornelia', 'Narita falls today. Darlton, Guilford: the slopes, in force.']],
        },
        {
          turn: 4,
          say: [
            ['zero', 'Kallen, now. Bring the mountain down on them.'],
            [null, 'A landslide pours down the southern slope. The Black Knights appear on the summit.'],
          ],
          blast: { c: 10, r: 8, damage: [0.7, 0.55, 0.4], sides: [B], terrain: 'plains', terrainRadius: 2, color: '#b08a5a', name: 'Landslide' },
          spawn: [
            [K, 'burai', 5, 1, 2, 'zero'],
            [K, 'elite_guren_mkii', 6, 2, 1, 'kallen'],
            [K, 'burai', 4, 2, 1, 'ohgi'],
            [K, 'burai', 7, 1, 1, 'tamaki'],
            [K, 'burai', 8, 2, 2, 'minami'],
          ],
        },
        {
          turn: 6,
          say: [['suzaku', 'Lancelot, deploying. Your Highness, I am coming.']],
          spawn: [[B, 'elite_lancelot', 11, 13, 1, 'suzaku']],
        },
      ],
    },
    {
      id: 'br5',
      title: 'The Black Rebellion',
      place: 'Tokyo Settlement',
      year: '2017 a.t.b.',
      brief:
        'The Black Knights storm the Tokyo Settlement. Hold the Government Bureau and the city’s districts until Suzaku and the Lancelot arrive.',
      unlock: 'Lancelot upgrades',
      player: B,
      sides: [B, K],
      map: TOKYO,
      cities: [
        ['Ashford Academy', 3, 7, K, 2],
        ['Settlement Gate', 8, 3, B, 1],
        ['Tokyo Tower', 12, 10, B, 2],
        ['Government Bureau', 18, 6, B, 3, { fort: true, gun: 'Government Bureau' }],
      ],
      economy: { britannia: 400, bk: 400 },
      industry: { britannia: 120, bk: 150 },
      production: [K],
      buildable: R1_BUILD,
      units: [
        [B, 'elite_cornelia_gloucester', 17, 6, 1, 'cornelia'],
        [B, 'gloucester', 12, 9, 2, 'guilford'],
        [B, 'gloucester', 9, 4, 2, 'darlton'],
        [B, 'sutherland', 8, 3, 2, 'villetta'],
        [B, 'sutherland', 12, 10, 2],
        [B, 'sutherland', 14, 6, 2],
        [B, 'sutherland', 16, 8, 1],
        [B, 'sutherland', 15, 3, 1],
        [B, 'glasgow', 10, 7, 1],
        [B, 'glasgow', 13, 4, 1],
        [K, 'elite_gawain', 4, 6, 1, 'zero'],
        [K, 'elite_guren_mkii', 5, 8, 1, 'kallen'],
        [K, 'elite_tohdoh_gekka', 5, 5, 1, 'tohdoh'],
        [K, 'gekka', 4, 9, 1, 'chiba'],
        [K, 'gekka', 6, 7, 1, 'asahina'],
        [K, 'burai', 3, 9, 2, 'ohgi'],
        [K, 'burai', 3, 5, 2, 'tamaki'],
        [K, 'gekka', 6, 4, 1, 'urabe'],
        [K, 'gekka', 6, 10, 1, 'senba'],
        [K, 'burai', 7, 8, 2, 'inoue'],
      ],
      objective: 'Hold the Government Bureau until the end of turn 10.',
      win: { hold: 10 },
      lose: { cities: ['Government Bureau'] },
      stars: [{ keep: ['Settlement Gate', 'Tokyo Tower', 'Government Bureau'] }, { kills: 12 }],
      victory: 'The rebellion breaks against the Bureau’s walls. Zero has vanished into the night.',
      events: [
        {
          turn: 1,
          say: [
            ['cornelia', 'The Elevens are in the Settlement. Not one step closer to the Bureau.'],
            ['zero', 'Black Knights! Tonight, Japan takes back Tokyo.'],
          ],
        },
        {
          turn: 3,
          say: [[null, 'More Black Knights pour in from the western ghettos.']],
          spawn: [
            [K, 'burai', 1, 4, 2],
            [K, 'burai_kai', 1, 9, 2],
          ],
        },
        {
          turn: 5,
          say: [['tohdoh', 'The second wave is here. Press the Bureau!']],
          spawn: [
            [K, 'gekka', 1, 6, 2],
            [K, 'burai', 1, 11, 2],
            [K, 'burai', 1, 2, 2],
          ],
        },
        {
          turn: 8,
          say: [['suzaku', 'Lancelot, entering the Settlement. Your Highness, I am here.']],
          spawn: [[B, 'elite_lancelot', 21, 7, 1, 'suzaku']],
        },
      ],
    },
    {
      id: 'br7',
      title: 'Return of the Black Knights',
      place: 'Tokyo outskirts',
      year: '2018 a.t.b.',
      brief:
        'Zero is back and the Black Knights are regrouping around the Chinese consulate. Protect the Sakuradite refinery, the rail hub and the power plant while they strike again and again.',
      unlock: 'Advanced research',
      player: B,
      sides: [B, K, 'cf'],
      teams: { bk: 'rebels', cf: 'rebels', britannia: 'empire' },
      names: { cf: { name: 'Chinese Consulate', short: 'Consulate', adj: 'Consulate' } },
      map: [
        'ppppppppuuuuuuuuuuuu',
        'pppppppuuuuxuuuuuuuu',
        'ppfffppuuuuuuuuuxuuu',
        'pfffffppuuuuuuuuuuuu',
        'ppfffpppppuuuuxuuuuu',
        'pppppppppppuuuuuuuuu',
        'pppppppppppppuuuuuuu',
        'ppffppppppppuuuuuuuu',
        'pffffpppppppuuuxuuuu',
        'ppfffpppppppuuuuuuuu',
        'pppppppppppppuuuuuuu',
        'ppppppppppppppuuuuuu',
      ],
      cities: [
        ['Chinese Consulate', 2, 6, 'cf', 1],
        ['Rail Hub', 10, 7, B, 1],
        ['Sakuradite Refinery', 14, 3, B, 2],
        ['Power Plant', 15, 9, B, 1],
        ['Settlement HQ', 18, 6, B, 2],
      ],
      economy: { britannia: 400 },
      industry: { britannia: 150 },
      hold: { cf: 1 },
      units: [
        [B, 'gloucester', 12, 5, 2, 'guilford'],
        [B, 'vincent_commander', 13, 8, 1, 'rolo'],
        [B, 'vincent_ward', 11, 3, 2],
        [B, 'vincent_ward', 14, 10, 2],
        [B, 'sutherland', 10, 6, 2, 'villetta'],
        [B, 'sutherland', 15, 2, 1],
        [B, 'sutherland', 16, 9, 1],
        [B, 'sutherland', 17, 5, 1],
        [K, 'burai', 4, 6, 2, 'zero'],
        [K, 'elite_guren_mkii', 5, 4, 1, 'kallen'],
        [K, 'burai', 4, 8, 1, 'cc'],
        [K, 'elite_tohdoh_gekka', 5, 7, 1, 'tohdoh'],
        [K, 'burai', 3, 3, 2],
        [K, 'burai', 3, 9, 2],
        ['cf', 'gun_ru', 2, 6, 2],
        ['cf', 'gun_ru', 1, 7, 1],
      ],
      objective: 'Hold out until the end of turn 10. The Sakuradite Refinery must not fall.',
      win: { hold: 10 },
      lose: { cities: ['Sakuradite Refinery'] },
      stars: [{ keep: ['Rail Hub', 'Sakuradite Refinery', 'Power Plant'] }, { kill: ['zero'] }],
      victory: 'The infrastructure holds. Zero’s raids cost him more than they cost the Empire.',
      events: [
        {
          turn: 1,
          say: [
            ['guilford', 'Zero has returned, and he will go for the refinery. We hold every site.'],
            ['zero', 'Britannia’s supply lines run through these three points. Take them.'],
          ],
        },
        {
          turn: 3,
          say: [[null, 'Black Knight reinforcements slip out of the consulate grounds.']],
          spawn: [
            [K, 'burai', 1, 4, 2],
            [K, 'burai_kai', 1, 8, 2],
          ],
        },
        {
          turn: 5,
          say: [['ohgi', 'The second group is ready. Moving out.']],
          spawn: [
            [K, 'burai', 1, 5, 1, 'ohgi'],
            [K, 'burai_kai', 1, 9, 2, 'sugiyama'],
            [K, 'burai_kai', 1, 3, 2, 'minami'],
          ],
        },
        {
          turn: 7,
          say: [['chiba', 'The Holy Swords are here. Let us finish this.']],
          spawn: [
            [K, 'gekka', 1, 6, 1, 'chiba'],
            [K, 'gekka', 1, 7, 1, 'asahina'],
          ],
        },
      ],
    },
    {
      id: 'br8',
      title: 'Second Battle of Tokyo',
      place: 'Tokyo Settlement',
      year: '2018 a.t.b.',
      brief:
        'The Black Knights attack Tokyo with Gefjun Disturbers that switch off whole sectors of your army. Hold the Government Bureau. Suzaku carries a weapon that must never be used.',
      unlock: 'F.L.E.I.J.A. project',
      player: B,
      sides: [B, K],
      map: TOKYO,
      cities: [
        ['Ikaruga Landing', 2, 7, K, 2],
        ['Settlement Gate', 8, 3, B, 1],
        ['Ashford Academy', 13, 6, B, 1],
        ['Tokyo Tower', 12, 10, B, 2],
        ['Government Bureau', 18, 6, B, 3, { fort: true, gun: 'Government Bureau' }],
      ],
      economy: { britannia: 400, bk: 500 },
      industry: { britannia: 150, bk: 200 },
      production: [K],
      units: [
        [B, 'elite_lancelot', 15, 7, 1, 'suzaku'],
        [B, 'brighton', 13, 4, 1, 'gino'],
        [B, 'elite_mordred', 17, 8, 1, 'anya'],
        [B, 'vincent_commander', 12, 9, 2, 'guilford'],
        [B, 'vincent_ward', 9, 4, 2],
        [B, 'vincent_ward', 11, 7, 2],
        [B, 'vincent_ward', 14, 11, 2],
        [B, 'vincent_ward', 16, 4, 2],
        [B, 'sutherland', 8, 3, 1],
        [B, 'sutherland', 12, 10, 1],
        [B, 'gareth', 19, 5, 1],
        [K, 'elite_shinkiro', 3, 6, 1, 'zero'],
        [K, 'elite_guren_mkii', 4, 8, 1, 'kallen'],
        [K, 'zangetsu', 4, 5, 1, 'tohdoh'],
        [K, 'akatsuki_zikisan', 5, 7, 1, 'chiba'],
        [K, 'akatsuki_zikisan', 3, 9, 1, 'asahina'],
        [K, 'akatsuki', 5, 4, 2, 'ohgi'],
        [K, 'akatsuki', 6, 6, 2, 'sugiyama'],
        [K, 'akatsuki', 5, 10, 2, 'minami'],
        [K, 'akatsuki', 6, 8, 2, 'senba'],
        [K, 'akatsuki_missile', 2, 5, 1],
      ],
      objective: 'Hold the Government Bureau until the end of turn 10.',
      win: { hold: 10 },
      lose: { cities: ['Government Bureau'] },
      stars: [{ kill: ['kallen'] }, { losses: 3 }],
      victory: 'The Bureau stands, in a city scarred forever by F.L.E.I.J.A.',
      events: [
        {
          turn: 1,
          say: [
            ['suzaku', 'The Black Knights are coming. Hold the Bureau; I will take the front.'],
            ['gino', 'Tristan and Mordred are with you. Let them come.'],
          ],
        },
        {
          turn: 3,
          say: [[null, 'A Gefjun Disturber switches on near Settlement Gate. Frames in the west sector shut down.']],
          stun: { c: 9, r: 4, radius: 2, sides: [B], name: 'Gefjun Disturber' },
        },
        {
          turn: 5,
          say: [[null, 'A second Disturber lights up by Tokyo Tower.']],
          stun: { c: 12, r: 10, radius: 2, sides: [B], name: 'Gefjun Disturber' },
          upgrade: { cmd: 'kallen', type: 'elite_guren_seiten' },
        },
        {
          turn: 6,
          say: [
            ['suzaku', 'The F.L.E.I.J.A. is armed... Everyone, get clear of the city center!'],
            [null, 'Warning: strategic weapon. Move your units out of the marked area.'],
          ],
          warn: { c: 9, r: 7, radius: 2, label: 'F.L.E.I.J.A.' },
        },
        {
          turn: 7,
          say: [
            [null, 'F.L.E.I.J.A. detonation. The heart of the Settlement disappears.'],
            ['suzaku', 'What... what have I done?'],
          ],
          blast: { c: 9, r: 7, damage: [1, 1, 0.6], terrain: 'crater', terrainRadius: 1, color: '#ffc4ec', name: 'F.L.E.I.J.A.' },
        },
      ],
    },
    {
      id: 'br9',
      title: 'Emperor Lelouch',
      place: 'Pendragon',
      year: '2018 a.t.b.',
      brief:
        'Lelouch vi Britannia has taken the throne. The Knights of the Round refuse to bow and march on the Imperial Palace. Command the Emperor’s new army: Suzaku in the Lancelot Albion, Jeremiah at his side.',
      unlock: 'Lancelot Albion and advanced frames',
      player: B,
      sides: [B, 'neutral'],
      names: { neutral: { name: 'Knights of the Round (rebels)', short: 'Rounds', adj: 'Rebel', color: '#e6dfc0' } },
      map: [
        'ffffpppppppppppppppfff',
        'fffpppuuuppppppppppfff',
        'ffppuuuuupppppppppppff',
        'fpppuuuuuppppfffpppppp',
        'ppppuuuuppppfffffppppp',
        'pppppuuppppppfffpppppp',
        'ppppppppppppppppppuupp',
        'pppfffppppppppppppuuup',
        'ppfffffppppmmmppppuupp',
        'pppfffpppppmmmmppppppp',
        'ppppppppppppmmpppppppp',
        'fppppppppppppppppppppf',
        'ffpppppppppppppppppfff',
      ],
      cities: [
        ['Pendragon Palace', 6, 3, B, 3, { fort: true, gun: 'Palace' }],
        ['Rebel Camp', 19, 7, 'neutral', 2],
      ],
      economy: { britannia: 500, neutral: 400 },
      industry: { britannia: 200, neutral: 150 },
      production: ['neutral'],
      units: [
        [B, 'elite_shinkiro', 4, 4, 1, 'lelouch'],
        [B, 'elite_lancelot_albion', 7, 5, 1, 'suzaku'],
        [B, 'vincent_commander', 6, 7, 2, 'jeremiah'],
        [B, 'vincent_ward', 8, 2, 2],
        [B, 'vincent_ward', 9, 4, 2],
        [B, 'vincent_ward', 8, 7, 2],
        [B, 'vincent_ward', 5, 9, 2],
        [B, 'gareth', 4, 6, 1],
        [B, 'gareth', 5, 1, 1],
        ['neutral', 'brighton', 17, 6, 1, 'bismarck'],
        ['neutral', 'vincent_commander', 16, 4, 2, 'monica'],
        ['neutral', 'vincent_commander', 16, 9, 2, 'dorothea'],
        ['neutral', 'vincent_commander', 14, 6, 2],
        ['neutral', 'gloucester', 15, 2, 2, 'nonette'],
        ['neutral', 'gloucester', 15, 11, 2],
        ['neutral', 'vincent_ward', 13, 3, 2],
        ['neutral', 'vincent_ward', 13, 9, 2],
        ['neutral', 'gareth', 18, 5, 1],
        ['neutral', 'gareth', 18, 9, 1],
      ],
      objective: 'Destroy Bismarck Waldstein’s unit. Lelouch must survive and the Palace must hold.',
      win: { kill: ['bismarck'] },
      lose: { cmd: ['lelouch'], cities: ['Pendragon Palace'], turns: 16 },
      stars: [{ turns: 10 }, { losses: 2 }],
      victory: 'The Knight of One falls to the Knight of Zero. The Empire belongs to Lelouch.',
      events: [
        {
          turn: 1,
          say: [
            ['bismarck', 'You are no emperor of ours. The Knights of the Round will remove you.'],
            ['monica', 'Knight of Twelve, ready. For the true Britannia.'],
            ['lelouch', 'Suzaku. Show them what the Knight of Zero can do.'],
            ['suzaku', 'Yes, Your Majesty.'],
          ],
        },
        {
          killed: 'bismarck',
          say: [['suzaku', 'It is over, Knight of One.']],
        },
      ],
    },
    {
      id: 'br10',
      title: 'Battle of Mount Fuji',
      place: 'Mount Fuji',
      year: '2018 a.t.b.',
      brief:
        'Schneizel, the Black Knights and the UFN gather beneath Mount Fuji. The mountain sits on the largest Sakuradite deposit on Earth. Capture the mine and you can set it off yourself.',
      unlock: 'Sakuradite Detonation',
      player: B,
      sides: [B, K, 'cf'],
      teams: { bk: 'ufn', cf: 'ufn', britannia: 'empire' },
      names: { cf: { name: 'UFN Federation Army', short: 'UFN', adj: 'UFN' } },
      map: FUJI,
      cities: [
        ['Ikaruga', 2, 6, K, 2, { fort: true, gun: 'Ikaruga' }],
        ['Fuji Sakuradite Mine', 11, 8, K, 1],
        ['Avalon Landing', 19, 5, B, 3, { fort: true, gun: 'Avalon' }],
      ],
      economy: { britannia: 500 },
      industry: { britannia: 200 },
      hold: { bk: 4 },
      units: [
        [B, 'elite_shinkiro', 19, 5, 1, 'lelouch'],
        [B, 'elite_lancelot_albion', 17, 6, 1, 'suzaku'],
        [B, 'vincent_commander', 17, 9, 2, 'jeremiah'],
        [B, 'vincent_ward', 16, 3, 2],
        [B, 'vincent_ward', 16, 8, 2],
        [B, 'vincent_ward', 18, 2, 2],
        [B, 'vincent_ward', 18, 10, 2],
        [B, 'gareth', 19, 7, 1],
        [B, 'gareth', 20, 4, 1],
        [B, 'gareth', 18, 6, 1],
        [K, 'elite_guren_seiten', 4, 5, 1, 'kallen', { hold: false }],
        [K, 'zangetsu', 4, 7, 1, 'tohdoh'],
        [K, 'akatsuki_zikisan', 5, 4, 1, 'chiba'],
        [K, 'akatsuki_zikisan', 5, 8, 1, 'asahina'],
        [K, 'akatsuki', 3, 8, 2, 'ohgi'],
        [K, 'akatsuki', 6, 6, 2],
        [K, 'akatsuki', 3, 4, 2],
        [K, 'brighton', 5, 9, 1, 'gino', { hold: false }],
        ['cf', 'shen_hu', 4, 10, 1, 'xingke'],
        ['cf', 'gun_ru', 5, 11, 2],
        ['cf', 'gun_ru', 6, 10, 2],
        ['cf', 'chuyen', 3, 11, 1],
      ],
      objective: 'Capture the Ikaruga. Lelouch must survive. Capturing the Fuji mine detonates it.',
      win: { capture: ['Ikaruga'] },
      lose: { cmd: ['lelouch'], cities: ['Avalon Landing'], turns: 18 },
      stars: [{ capture: ['Fuji Sakuradite Mine'], text: 'Detonate the Fuji mine' }, { turns: 14 }],
      victory: 'The Ikaruga is taken. With Fuji’s fire behind him, the Emperor turns to Damocles.',
      events: [
        {
          turn: 1,
          say: [
            ['lelouch', 'The mine under Fuji holds more Sakuradite than all the world’s other deposits combined.'],
            ['lelouch', 'Take it, and we can turn the mountain itself against them. Clear our own units first.'],
            ['kallen', 'Suzaku is out there. Everyone, hold the line around the Ikaruga!'],
          ],
          warn: { c: 11, r: 6, radius: 2, label: 'Mine charge' },
        },
        {
          capture: 'Fuji Sakuradite Mine',
          by: B,
          say: [
            ['lelouch', 'Detonate the mine.'],
            [null, 'The Sakuradite under Fuji ignites. The mountain’s heart explodes outward.'],
          ],
          blast: { c: 11, r: 6, damage: [1, 0.85, 0.55], terrain: 'crater', terrainRadius: 1, color: '#ff9ad5', name: 'Sakuradite detonation' },
        },
      ],
    },
    {
      id: 'br11',
      title: 'Assault on Damocles',
      place: 'Skies over Mount Fuji',
      year: '2018 a.t.b.',
      brief:
        'Schneizel’s Damocles hides behind a Blaze Luminous barrier and rains F.L.E.I.J.A. on whatever approaches. Destroy its four barrier generators, survive the launches, and storm the fortress.',
      unlock: 'Campaign complete',
      player: B,
      sides: [B, 'neutral', K],
      teams: { neutral: 'damocles', bk: 'damocles', britannia: 'empire' },
      names: { neutral: { name: 'Damocles', short: 'Damocles', adj: 'Damocles', color: '#c8d4e8' } },
      map: SKY,
      cities: [
        ['Avalon', 12, 12, B, 3, { fort: true, gun: 'Avalon' }],
        ['Generator West', 7, 3, 'neutral', 1],
        ['Generator North', 17, 2, 'neutral', 1],
        ['Generator South-West', 5, 6, 'neutral', 1],
        ['Generator East', 19, 5, 'neutral', 1],
        ['Damocles', 12, 1, 'neutral', 3, { fort: true, gun: 'Damocles', shield: 1500 }],
      ],
      economy: { britannia: 500 },
      industry: { britannia: 200 },
      hold: { neutral: 2 },
      units: [
        [B, 'elite_shinkiro', 12, 12, 1, 'lelouch'],
        [B, 'elite_lancelot_albion', 12, 10, 1, 'suzaku'],
        [B, 'vincent_commander', 10, 11, 2, 'jeremiah'],
        [B, 'vincent_ward', 8, 11, 2],
        [B, 'vincent_ward', 15, 11, 2],
        [B, 'vincent_ward', 9, 9, 2],
        [B, 'vincent_ward', 15, 9, 2],
        [B, 'gareth', 11, 12, 1],
        [B, 'gareth', 13, 11, 1],
        [B, 'gareth', 17, 10, 1],
        ['neutral', 'gareth', 12, 1, 1, 'schneizel', { hold: 1 }],
        ['neutral', 'vincent_commander', 7, 3, 1, null, { hold: 1 }],
        ['neutral', 'vincent_commander', 17, 2, 1, null, { hold: 1 }],
        ['neutral', 'vincent_ward', 5, 6, 1, null, { hold: 1 }],
        ['neutral', 'vincent_ward', 19, 5, 1, null, { hold: 1 }],
        [K, 'elite_guren_seiten', 12, 4, 1, 'kallen', { hold: 4 }],
        [K, 'zangetsu', 10, 3, 1, 'tohdoh', { hold: 3 }],
        [K, 'akatsuki_zikisan', 14, 3, 1, 'chiba', { hold: 3 }],
        [K, 'akatsuki_zikisan', 9, 5, 1, 'asahina', { hold: 3 }],
        [K, 'akatsuki', 15, 5, 2, null, { hold: 3 }],
        [K, 'akatsuki', 11, 6, 2, null, { hold: 3 }],
      ],
      objective: 'Capture Damocles. Each barrier generator you take weakens its Blaze Luminous. Lelouch must survive.',
      win: { capture: ['Damocles'] },
      lose: { cmd: ['lelouch'], turns: 20 },
      stars: [{ capture: ['Generator West', 'Generator North', 'Generator South-West', 'Generator East'] }, { losses: 3 }],
      victory: 'Damocles is yours. The world’s last weapon now answers to the Emperor alone.',
      events: [
        {
          turn: 1,
          say: [
            ['schneizel', 'Damocles is the key to peace, Lelouch. You cannot reach it.'],
            ['lelouch', 'Then I will tear down its barrier one generator at a time.'],
          ],
        },
        ...['West', 'North', 'South-West', 'East'].map(p => ({
          capture: `Generator ${p}`,
          by: B,
          say: [[null, `Generator ${p} destroyed. Damocles’s Blaze Luminous flickers.`]],
          shield: { city: 'Damocles', cut: 375 },
        })),
        ...[
          [2, 12, 8],
          [5, 10, 10],
          [8, 15, 7],
          [11, 9, 6],
        ].flatMap(([t, c, r]) => [
          {
            turn: t,
            say: [[null, 'F.L.E.I.J.A. launch detected. Impact next turn in the marked area.']],
            warn: { c, r, radius: 2, label: 'F.L.E.I.J.A.' },
          },
          {
            turn: t + 1,
            say: [[null, 'F.L.E.I.J.A. impact.']],
            blast: { c, r, damage: [1, 1, 0.6], terrain: 'crater', color: '#ffc4ec', name: 'F.L.E.I.J.A.' },
          },
        ]),
      ],
    },
  ];

  // Britannia's 2017 lineup for the first-season missions added with the season split.
  const S1_BRIT = { britannia: ['glasgow', 'sutherland', 'gloucester', 'gracchus'] };
  const REBELS = { bk: 'rebels', jlf: 'rebels', cf: 'rebels', britannia: 'empire' };

