  const EXTRA = [
    {
      id: 'br_mef',
      title: 'Middle Eastern Federation Skirmish',
      place: 'Area 18, Middle Eastern Federation',
      year: '2017 a.t.b.',
      brief:
        'The Middle Eastern Federation makes its last stand behind four Bamides and their long-range guns. Its fire has already torn apart the first Sutherland brigade. Cornelia circles the position while Guilford and Darlton prepare the finishing charge.',
      unlock: 'Cornelia transfers to Area 11',
      player: B,
      sides: [B, 'neutral'],
      names: { neutral: { name: 'Middle Eastern Federation', short: 'M.E.F.', adj: 'M.E.F.', color: '#d6a85f' } },
      map: MEF_FORTRESS,
      cities: [
        ['Britannian Staging Ground', 2, 9, B, 1],
        ['Bamides Gun Line', 14, 6, 'neutral', 1],
        ['M.E.F. Fortress', 15, 7, 'neutral', 2, { fort: true, gun: 'Fortress' }],
      ],
      economy: { britannia: 260 },
      hold: { neutral: 2 },
      units: [
        [B, 'elite_cornelia_gloucester', 4, 9, 1, 'cornelia'],
        [B, 'gloucester', 5, 8, 1, 'guilford'],
        [B, 'gloucester', 5, 10, 1, 'darlton'],
        [B, 'sutherland', 3, 7, 2],
        [B, 'sutherland', 3, 10, 2],
        [B, 'sutherland', 6, 11, 1, null, { normalOnly: true }],
        ['neutral', 'bamides', 13, 6, 1, null, { hold: 1 }],
        ['neutral', 'bamides', 16, 6, 1, null, { hold: 1 }],
        ['neutral', 'bamides', 14, 8, 1, null, { hold: 1 }],
        ['neutral', 'bamides', 17, 8, 1, null, { hold: 1 }],
        ['neutral', 'bamides', 18, 6, 1, null, { skipNormal: true }],
      ],
      objective: 'Capture the M.E.F. Fortress. Cornelia must survive.',
      win: { capture: ['M.E.F. Fortress'] },
      lose: { cmd: ['cornelia'], turns: 13 },
      stars: [{ alive: ['guilford', 'darlton'] }, { turns: 8 }],
      victory: 'The fortress falls and the last Bamides are destroyed. Britannia declares Area 18 secure, freeing Cornelia to depart for Area 11.',
      events: [
        {
          turn: 1,
          say: [
            ['darlton', 'Their long-range guns gutted the first brigade. A frontal attack is exactly what they want.'],
            ['cornelia', 'Then Guilford takes the front and I take their fortress from the flank. Move.'],
          ],
        },
      ],
    },
    {
      id: 'bk_rescue',
      title: "Black Knights' Rescue Operation",
      place: 'Chinese Consulate district, Tokyo',
      year: '2018 a.t.b.',
      brief:
        'Guilford has put the captured Black Knights on an execution platform beside the Chinese Consulate to lure Zero into a duel. Break the trap, free Tohdoh and Ohgi, then get the prisoners across the diplomatic line.',
      unlock: 'The Black Knights reunite',
      player: K,
      sides: [K, 'cf', B],
      teams: { bk: 'rebels', cf: 'rebels', britannia: 'empire' },
      names: { cf: { name: 'Chinese Consulate', short: 'Consulate', adj: 'Consulate' } },
      map: GALLOWS,
      cities: [
        ['Zero Entry', 2, 5, K, 1],
        ['Execution Ground', 10, 5, B, 1],
        ['G-1 Base', 14, 6, B, 2],
        ['Chinese Consulate', 19, 8, 'cf', 1],
      ],
      economy: { bk: 220 },
      hold: { britannia: 2, cf: 1 },
      units: [
        [K, 'burai', 2, 5, 1, 'zero'],
        [K, 'elite_guren_mkii', 18, 9, 1, 'kallen'],
        [K, 'burai', 18, 8, 1, 'cc'],
        ['cf', 'gun_ru', 19, 9, 1],
        [B, 'gloucester', 9, 5, 1, 'guilford'],
        [B, 'gloucester', 11, 4, 1],
        [B, 'gloucester', 12, 6, 1],
        [B, 'sutherland', 8, 3, 2],
        [B, 'sutherland', 13, 3, 2],
        [B, 'sutherland', 15, 7, 2],
        [B, 'vincent_commander', 16, 5, 1, 'rolo'],
        [B, 'sutherland', 7, 8, 1, null, { skipNormal: true }],
      ],
      objective: 'Capture the Execution Ground, then reach the Chinese Consulate. Zero must survive.',
      win: [{ capture: ['Execution Ground'] }, { reach: ['Chinese Consulate'] }],
      lose: { cmd: ['zero'], turns: 14 },
      stars: [{ alive: ['tohdoh', 'ohgi'] }, { turns: 9 }],
      victory: 'The prisoners cross into Chinese territory and Guilford is forced to withdraw. The Black Knights are whole again.',
      events: [
        {
          turn: 1,
          say: [
            ['guilford', 'Zero! Face me alone, or the prisoners die here.'],
            ['zero', 'One weapon each, Guilford. I accept.'],
          ],
        },
        {
          capture: 'Execution Ground',
          by: K,
          say: [
            ['zero', 'Now. Drop the platform toward the consulate!'],
            ['kallen', 'Black Knights, charge!'],
          ],
          blast: { c: 11, r: 5, damage: [0.7, 0.35], sides: [B], color: '#d8c49a', name: 'Collapsing execution platform' },
          spawn: [
            [K, 'elite_tohdoh_gekka', 18, 7, 1, 'tohdoh'],
            [K, 'burai', 18, 8, 1, 'ohgi'],
            [K, 'burai_kai', 17, 8, 1, 'chiba'],
            [K, 'burai_kai', 17, 9, 1, 'asahina'],
          ],
          note: 'The prisoners are free. Get one Black Knight unit to the Chinese Consulate.',
        },
      ],
    },
    {
      id: 'bk_zhengzhou',
      title: 'Skirmish at Zhengzhou',
      place: 'Zhengzhou, Chinese Federation',
      year: '2018 a.t.b.',
      brief:
        'Zero has taken Empress Tianzi from the political marriage ceremony. The Black Knights race west from Zhengzhou while Li Xingke takes the Shen Hu and predicts every escape route. Break through before he closes the trap.',
      unlock: 'Road to Xiaopei',
      player: K,
      sides: [K, 'neutral'],
      names: { neutral: { name: 'Chinese Federation Loyalists', short: 'Loyalists', adj: 'Loyalist', color: '#d6b654' } },
      map: ZHENGZHOU,
      cities: [
        ['Tianzi Convoy', 3, 6, K, 1],
        ['Zhengzhou Garrison', 11, 5, 'neutral', 2],
        ['Xiaopei Road', 19, 6, K, 1],
      ],
      economy: { bk: 260 },
      hold: { neutral: 2 },
      units: [
        [K, 'zangetsu', 4, 5, 1, 'tohdoh'],
        [K, 'elite_guren_mkii', 4, 7, 1, 'kallen'],
        [K, 'akatsuki_zikisan', 3, 4, 1, 'chiba'],
        [K, 'akatsuki_zikisan', 3, 8, 1, 'asahina'],
        [K, 'akatsuki', 2, 6, 2, 'ohgi'],
        [K, 'akatsuki', 5, 6, 2],
        [K, 'akatsuki', 2, 9, 1, null, { normalOnly: true }],
        ['neutral', 'gun_ru', 10, 4, 2],
        ['neutral', 'gun_ru', 11, 7, 2],
        ['neutral', 'gun_ru', 13, 3, 2],
        ['neutral', 'gun_ru', 14, 8, 2],
        ['neutral', 'elite_shen_hu', 15, 6, 1, 'xingke'],
        ['neutral', 'gun_ru', 16, 5, 1, 'xianglin'],
        ['neutral', 'gun_ru', 16, 8, 1, null, { skipNormal: true }],
      ],
      objective: 'Reach the Xiaopei Road. Kallen and Tohdoh must survive.',
      win: { reach: ['Xiaopei Road'] },
      lose: { cmd: ['kallen', 'tohdoh'], turns: 13 },
      stars: [{ keep: ['Tianzi Convoy'] }, { turns: 8 }],
      victory: 'The Black Knights break out of Zhengzhou and continue toward Xiaopei, but Xingke is already moving to cut them off again.',
      events: [
        {
          turn: 1,
          say: [
            ['zero', 'The Empress is with us. We break west before the Federation can surround Zhengzhou.'],
            ['xingke', 'Zero, you took Tianzi from the Forbidden City. I will predict every road you take.'],
          ],
        },
      ],
    },
    {
      id: 'br_kamejima',
      title: 'Second Battle of Kamejima Island',
      place: 'Kamejima Island',
      year: '2018 a.t.b.',
      brief:
        'After Tokyo, Lelouch turns on Charles himself. Geass-controlled Britannian crews attack the Emperor’s armada while Lelouch races toward the Thought Elevator. Suzaku arrives with the same conclusion: Ragnarök must be stopped.',
      unlock: 'Lelouch takes the throne',
      player: B,
      sides: [B, 'neutral'],
      names: { neutral: { name: 'Charles Loyalists', short: 'Loyalists', adj: 'Loyalist', color: '#c7b7de' } },
      map: KAMEJIMA,
      cities: [
        ['Geassed Landing', 5, 9, B, 1],
        ['Imperial Landing', 15, 2, 'neutral', 2],
        ['Thought Elevator', 10, 6, 'neutral', 3, { fort: true, gun: 'Thought Elevator' }],
      ],
      economy: { britannia: 260 },
      hold: { neutral: 2 },
      units: [
        [B, 'elite_shinkiro', 5, 9, 1, 'lelouch'],
        [B, 'vincent_ward', 6, 8, 2],
        [B, 'vincent_ward', 4, 8, 1],
        [B, 'sutherland_air', 6, 10, 1],
        ['neutral', 'brighton', 14, 4, 1, 'bismarck'],
        ['neutral', 'vincent_commander', 15, 5, 1, 'monica'],
        ['neutral', 'elite_mordred', 13, 6, 1, 'anya'],
        ['neutral', 'vincent_ward', 11, 4, 2],
        ['neutral', 'vincent_ward', 12, 8, 2],
        ['neutral', 'gareth', 10, 5, 1, null, { hold: 1 }],
        ['neutral', 'vincent_ward', 16, 7, 1, null, { skipNormal: true }],
      ],
      objective: 'Reach the Thought Elevator. Lelouch must survive.',
      win: { reach: ['Thought Elevator'] },
      lose: { cmd: ['lelouch'], turns: 13 },
      stars: [{ alive: ['suzaku'] }, { turns: 8 }],
      victory: 'Lelouch reaches C’s World and rejects the Ragnarök Connection. Charles and Marianne disappear, and the old imperial order dies with them.',
      events: [
        {
          turn: 1,
          say: [
            ['lelouch', 'The Emperor is on Kamejima. Every ship and soldier I have Geassed—turn your guns on his loyalists.'],
            ['suzaku', 'Lelouch. Geass caused this ruin for both of us. I will help you end it.'],
            ['bismarck', 'Protect His Majesty. No rebel reaches the Thought Elevator.'],
          ],
          spawn: [[B, 'elite_lancelot_albion', 5, 10, 1, 'suzaku']],
        },
      ],
    },
    {
      id: 'bk_yokosuka',
      title: 'Battle of Port Yokosuka',
      place: 'Port Yokosuka, Area 11',
      year: '2017 a.t.b.',
      brief:
        'Katase means to slip the JLF out of Area 11 on a tanker full of Sakuradite, but Cornelia has the pier surrounded. Zero has a plan for the tanker, and for Cornelia.',
      unlock: 'Katase’s Sakuradite',
      player: K,
      sides: [K, 'jlf', B],
      teams: REBELS,
      map: YOKOSUKA,
      cities: YOKOSUKA_CITIES,
      economy: { bk: 250 },
      buildable: R1_BUILD,
      hold: { britannia: 2, jlf: 1 },
      units: [
        ...YOKOSUKA_BK,
        [K, 'burai', 1, 2, 1, null, { normalOnly: true }],
        ...YOKOSUKA_JLF,
        ...YOKOSUKA_BRIT,
        [B, 'sutherland', 12, 3, 2, null, { skipNormal: true }],
        [B, 'gracchus', 14, 5, 1, null, { skipNormal: true }],
      ],
      objective: 'Wait for the blockade to break, then capture Cornelia’s G-1. Zero must survive.',
      win: { capture: ['Cornelia’s G-1'] },
      lose: { cmd: ['zero'], turns: 14 },
      stars: [{ kill: ['cornelia'] }, { losses: 2 }],
      victory: 'The G-1 falls. Cornelia escapes only because the Lancelot cuts its way to her.',
      events: [
        {
          turn: 1,
          say: [
            ['katase', 'The tanker is loaded. We break out tonight, whatever Cornelia throws at us.'],
            ['zero', 'Katase is boxed in at the pier. Black Knights, hold position until my signal.'],
          ],
        },
        {
          turn: 3,
          say: [
            ['zero', 'Katase, forgive me. Your death will open the way.'],
            [null, 'The JLF tanker explodes. The blockade on the pier is shattered.'],
          ],
          blast: TANKER_BLAST,
          note: 'Strike while Cornelia reels: capture her G-1. Zero must survive.',
        },
        {
          turn: 4,
          say: [
            ['suzaku', 'Princess Cornelia, hold on. Lancelot, launching!'],
            ['kallen', 'The white Knightmare again. Leave him to me, Zero!'],
          ],
          spawn: [[B, 'elite_lancelot', 20, 6, 1, 'suzaku']],
        },
      ],
    },
    {
      id: 'bk_tohdoh',
      title: 'Rescue of Tohdoh',
      place: 'Chofu Detention Center, Tokyo',
      year: '2017 a.t.b.',
      brief:
        'Kyoshiro Tohdoh, the Miracle of Itsukushima, is to be executed at dawn. The Four Holy Swords join the Black Knights to break him out of Chofu, and Kallen has brought him a Gekka.',
      unlock: 'Tohdoh, his Gekka and the Four Holy Swords',
      player: K,
      sides: [K, B],
      map: CHOFU,
      cities: CHOFU_CITIES,
      economy: { bk: 250 },
      buildable: R1_BUILD,
      hold: { britannia: 3 },
      units: [
        ...CHOFU_BK,
        [K, 'burai', 1, 10, 1, null, { normalOnly: true }],
        ...CHOFU_BRIT,
        [B, 'glasgow', 11, 9, 1, null, { skipNormal: true }],
        [B, 'sutherland', 16, 2, 1, null, { skipNormal: true }],
      ],
      objective: 'Break into the Chofu Detention Center to free Tohdoh, then reach the escape route. Zero must survive.',
      win: [{ capture: ['Chofu Detention Center'] }, { reach: ['Escape Route'], by: 'tohdoh' }],
      lose: { cmd: ['zero', 'tohdoh'], turns: 14 },
      stars: [{ turns: 9 }, { alive: ['chiba', 'asahina', 'senba', 'urabe'] }],
      victory: 'Tohdoh and the Four Holy Swords join the Black Knights. Britannia has made a dangerous enemy.',
      events: [
        {
          turn: 1,
          say: [
            ['zero', 'Tohdoh hangs at dawn. We take him back before the sun comes up.'],
            ['chiba', 'Colonel, wait for us. We will not let them kill you.'],
          ],
        },
        {
          turn: 3,
          say: [
            ['suzaku', 'Major Tohdoh taught me everything. But orders are orders.'],
            ['zero', 'The Lancelot. Keep it away from the detention center!'],
          ],
          spawn: [[B, 'elite_lancelot', 21, 6, 1, 'suzaku']],
        },
        {
          capture: 'Chofu Detention Center',
          by: K,
          say: [
            ['tohdoh', 'Zero. I owe you my life, so I will fight for you, starting now.'],
            ['kallen', 'Colonel, your Gekka is ready. We brought it for you.'],
          ],
          spawn: [[K, 'elite_tohdoh_gekka', 12, 5, 1, 'tohdoh']],
          note: 'Tohdoh is free. Reach the escape route. Zero and Tohdoh must survive.',
        },
      ],
    },
    {
      id: 'bk_shikine',
      title: 'Shikine and Kamine Islands',
      place: 'Shikine and Kamine Islands',
      year: '2017 a.t.b.',
      brief:
        'Zero lures Suzaku to Shikine Island and springs a Gefjun trap on the Lancelot. Schneizel answers with a bombardment that would kill them both, and across the strait, Kamine Island hides Britannia’s newest frame.',
      unlock: 'Gawain',
      player: K,
      sides: [K, B],
      map: SHIKINE,
      cities: SHIKINE_CITIES,
      economy: { bk: 300 },
      buildable: R1_BUILD,
      hold: { britannia: 3 },
      units: [
        ...SHIKINE_BK,
        [K, 'burai', 2, 5, 1, null, { normalOnly: true }],
        ...SHIKINE_BRIT,
        [B, 'glasgow', 19, 7, 1, null, { skipNormal: true }],
        [B, 'sutherland', 8, 8, 1, null, { skipNormal: true }],
      ],
      objective: 'Trap the Lancelot, survive the bombardment, then capture the Kamine Ruins and Kamine Landing. Zero must survive.',
      win: { capture: ['Kamine Ruins', 'Kamine Landing'] },
      lose: { cmd: ['zero'], turns: 16 },
      stars: [{ kill: ['suzaku'] }, { losses: 2 }],
      victory: 'Zero leaves Kamine Island in the Gawain. Schneizel’s prototype now flies for the Black Knights.',
      events: [
        {
          turn: 1,
          say: [
            ['zero', 'Suzaku will come to Shikine alone. When he does, the Gefjun Disturbers close the trap.'],
            ['suzaku', 'Zero is on this island. I will bring him in myself.'],
          ],
        },
        {
          turn: 2,
          say: [
            [null, 'The Gefjun Disturbers fire. The Lancelot locks up.'],
            ['zero', 'Suzaku. Join me, or be taken.'],
          ],
          stun: GEFJUN_TRAP,
        },
        {
          turn: 3,
          say: [
            ['schneizel', 'Zero is pinned on Shikine. Bombard the area. The Lancelot is an acceptable loss.'],
            ['Euphemia@britannia', 'Brother, Suzaku is down there! Stop this!'],
          ],
          warn: { c: 7, r: 4, radius: 2, label: 'Bombardment' },
        },
        {
          turn: 4,
          say: [[null, 'The bombardment hits Shikine. In the confusion, the ruins on Kamine Island lie open.']],
          blast: { c: 7, r: 4, damage: [0.8, 0.6, 0.4], color: '#ffb36b', name: 'Bombardment' },
          note: 'Capture the Kamine Ruins, then the Kamine Landing. Zero must survive.',
        },
        {
          capture: 'Kamine Ruins',
          by: K,
          say: [
            ['cc', 'Schneizel’s new frame, left in the ruins. The Gawain is ours now.'],
            ['zero', 'With the Gawain, Britannia’s landing is next.'],
          ],
          upgrade: { cmd: 'zero', type: 'elite_gawain' },
        },
      ],
    },
    {
      id: 'bk_fukuoka',
      title: 'Battle of Fukuoka Base',
      place: 'Fukuoka Base, Kyushu',
      year: '2017 a.t.b.',
      brief:
        'Sawasaki seizes Fukuoka with Chinese Federation troops and declares an independent Japan under Federation protection. Suzaku attacks alone through the storm, and Zero arrives in the Gawain. Today Britannia is not the enemy.',
      unlock: 'An uneasy truce',
      player: K,
      sides: [K, B, 'cf'],
      teams: { bk: 'allies', britannia: 'allies', cf: 'sawasaki' },
      names: SAWASAKI,
      map: FUKUOKA,
      cities: FUKUOKA_CITIES,
      economy: { bk: 300 },
      buildable: R1_BUILD,
      hold: { cf: 3 },
      units: [
        ...FUKUOKA_BK,
        [K, 'gekka', 1, 8, 1, null, { normalOnly: true }],
        ...FUKUOKA_BRIT,
        ...FUKUOKA_CF,
        ['cf', 'gun_ru', 6, 6, 1, null, { skipNormal: true }],
        ['cf', 'gun_ru', 14, 6, 1, null, { skipNormal: true }],
      ],
      objective: 'Destroy Sawasaki’s Federation army. Britannia fights beside you today. Zero must survive.',
      win: { destroy: ['cf'] },
      lose: { cmd: ['zero'], turns: 14 },
      stars: [{ capture: ['Fukuoka Base'] }, { alive: ['suzaku'] }],
      victory: 'Sawasaki’s Japan collapses in a day. Zero and Suzaku fought back to back, and both will remember it.',
      events: [
        {
          turn: 1,
          say: [
            ['Sawasaki@cf', 'From Fukuoka, Japan is reborn as an independent nation, under the Federation’s protection.'],
            ['zero', 'A Federation puppet wearing Japan’s name. Black Knights, we fight beside Britannia today.'],
            ['suzaku', 'Zero? ...Fine. Fukuoka first.'],
          ],
        },
        FUKUOKA_REINFORCE,
      ],
    },
    {
      id: 'bk_saz',
      title: 'Special Administrative Zone',
      place: 'SAZ ceremony grounds, Mount Fuji',
      year: '2017 a.t.b.',
      brief:
        'Euphemia’s Special Administrative Zone was meant to bring Japanese and Britannians together. At the ceremony, her order turns Britannian guns on the crowd. The Black Knights must protect the Japanese and reach her.',
      unlock: 'The United States of Japan is proclaimed',
      player: K,
      sides: [K, B],
      map: SAZ,
      cities: [
        ['Black Knights Line', 11, 1, K, 2],
        ['Refugee Camp West', 3, 7, K, 1],
        ['SAZ Stadium', 11, 5, B, 3],
        ['Refugee Camp East', 18, 7, K, 1],
        ['Britannian Garrison', 11, 11, B, 2],
      ],
      economy: { bk: 300 },
      buildable: R1_BUILD,
      goals: { britannia: [[3, 7, -6], [18, 7, -6]] },
      units: [
        [K, 'elite_gawain', 11, 1, 1, 'zero'],
        [K, 'elite_guren_mkii', 10, 2, 1, 'kallen'],
        [K, 'elite_tohdoh_gekka', 12, 2, 1, 'tohdoh'],
        [K, 'gekka', 9, 1, 1, 'chiba'],
        [K, 'gekka', 13, 1, 1, 'asahina'],
        [K, 'gekka', 8, 2, 1, 'senba'],
        [K, 'gekka', 14, 2, 1, 'urabe'],
        [K, 'burai', 10, 0, 2, 'ohgi'],
        [K, 'burai', 4, 7, 1, 'tamaki'],
        [K, 'burai', 17, 7, 1, 'sugiyama'],
        [K, 'gekka', 12, 0, 1, null, { normalOnly: true }],
        [B, 'sutherland', 11, 5, 2, null, { hold: 1 }],
        [B, 'gloucester', 9, 4, 2],
        [B, 'gloucester', 13, 4, 2],
        [B, 'sutherland', 7, 6, 2, null, { hold: false }],
        [B, 'sutherland', 15, 6, 2, null, { hold: false }],
        [B, 'sutherland', 6, 8, 1, null, { hold: false }],
        [B, 'sutherland', 16, 8, 1, null, { hold: false }],
        [B, 'glasgow', 11, 11, 2],
        [B, 'sutherland', 12, 10, 1, null, { skipNormal: true }],
        [B, 'glasgow', 10, 9, 1, null, { skipNormal: true }],
      ],
      objective: 'Capture the SAZ Stadium and protect the refugee camps. Zero must survive.',
      win: { capture: ['SAZ Stadium'] },
      lose: { cmd: ['zero'], turns: 15 },
      stars: [{ keep: ['Refugee Camp West', 'Refugee Camp East'] }, { turns: 9 }],
      victory: 'Zero reaches Euphemia. The Special Administrative Zone dies with her, and Japan rises behind the Black Knights.',
      events: [
        {
          turn: 1,
          say: [
            ['Euphemia@britannia', 'Soldiers of Britannia... the Japanese here must all die.'],
            ['zero', 'Euphie... this is my doing. Black Knights! Protect the Japanese. Every unit, strike the stadium!'],
          ],
        },
        {
          turn: 3,
          say: [['suzaku', 'Euphie, what is happening? Stop, all of you, stop!']],
          spawn: [[B, 'elite_lancelot', 11, 12, 1, 'suzaku']],
        },
      ],
    },
    {
      id: 'br_yokosuka',
      title: 'Port Yokosuka Blockade',
      place: 'Port Yokosuka, Area 11',
      year: '2017 a.t.b.',
      brief:
        'The JLF’s Katase is trying to flee Area 11 on a tanker loaded with Sakuradite. Cornelia has the pier surrounded, and the Black Knights are somewhere in the dark.',
      unlock: 'The JLF’s last stand',
      player: B,
      sides: [B, 'jlf', K],
      teams: REBELS,
      map: YOKOSUKA,
      cities: YOKOSUKA_CITIES,
      economy: { britannia: 300 },
      buildable: S1_BRIT,
      hold: { jlf: 1 },
      goals: { bk: [[18, 4, -6]] },
      units: [...YOKOSUKA_BRIT, [B, 'sutherland', 15, 5, 1, null, { normalOnly: true }], ...YOKOSUKA_JLF],
      objective: 'Crush the JLF at the pier, then hold the G-1 until the end of turn 8. Cornelia must survive.',
      win: [{ destroy: ['jlf'] }, { hold: 8 }],
      lose: { cmd: ['cornelia'], cities: ['Cornelia’s G-1'] },
      stars: [{ kill: ['kallen'] }, { losses: 3 }],
      victory: 'Katase is dead and the Black Knights fall back. The Lancelot reached the princess in time.',
      events: [
        {
          turn: 1,
          say: [
            ['cornelia', 'The JLF think they can run with Japan’s Sakuradite. Tighten the blockade.'],
            ['darlton', 'Our Sutherlands hold the pier, Your Highness.'],
          ],
        },
        {
          turn: 3,
          say: [
            [null, 'The tanker explodes! Britannian units on the pier are caught in the blast.'],
            ['zero', 'Cornelia! Tonight your army is mine to break.'],
          ],
          blast: TANKER_BLAST,
          spawn: [...YOKOSUKA_BK, [K, 'burai', 1, 2, 1, null, { skipNormal: true }]],
          note: 'The Black Knights are attacking. Keep Cornelia alive and hold the G-1 until the end of turn 8.',
        },
        {
          turn: 5,
          say: [['suzaku', 'Princess Cornelia, I’m on my way. Lancelot, launching!']],
          spawn: [[B, 'elite_lancelot', 20, 6, 1, 'suzaku']],
        },
      ],
    },
    {
      id: 'br_tohdoh',
      title: 'Chofu Detention Center',
      place: 'Chofu Detention Center, Tokyo',
      year: '2017 a.t.b.',
      brief:
        'Kyoshiro Tohdoh is to be executed at dawn. Intelligence says the Black Knights and the Four Holy Swords will try to break him out. Hold the detention center until the sentence is carried out.',
      unlock: 'The Lancelot’s reputation',
      player: B,
      sides: [B, K],
      map: CHOFU,
      cities: CHOFU_CITIES,
      economy: { britannia: 250 },
      buildable: S1_BRIT,
      goals: { bk: [[12, 5, -6]] },
      units: [...CHOFU_BRIT, [B, 'sutherland', 11, 4, 1, null, { normalOnly: true }], ...CHOFU_BK, [K, 'burai', 1, 10, 1, null, { skipNormal: true }]],
      objective: 'Hold the Chofu Detention Center until the end of turn 9.',
      win: { hold: 9 },
      lose: { cities: ['Chofu Detention Center'] },
      stars: [{ kill: ['kallen'] }, { keep: ['Outer Checkpoint'] }],
      victory: 'The Black Knights break off. Tohdoh stays behind bars, for now.',
      events: [
        {
          turn: 1,
          say: [
            ['villetta', 'If the Black Knights come for Tohdoh, the checkpoint will be ready for them.'],
            ['zero', 'Black Knights, the detention center. Now!'],
          ],
        },
        {
          turn: 3,
          say: [['suzaku', 'Major Tohdoh was my teacher. I won’t let anyone use him as a symbol.']],
          spawn: [[B, 'elite_lancelot', 21, 6, 1, 'suzaku']],
        },
      ],
    },
    {
      id: 'br_shikine',
      title: 'Shikine and Kamine Islands',
      place: 'Shikine and Kamine Islands',
      year: '2017 a.t.b.',
      brief:
        'Zero has called Suzaku to Shikine Island. It is a trap, but it is also the best chance Britannia has had to take Zero. Kamine Island, across the strait, hides Schneizel’s Gawain.',
      unlock: 'Schneizel takes notice',
      player: B,
      sides: [B, K],
      map: SHIKINE,
      cities: SHIKINE_CITIES,
      economy: { britannia: 300 },
      buildable: S1_BRIT,
      goals: { bk: [[17, 4, -6]] },
      units: [...SHIKINE_BRIT, [B, 'gloucester', 16, 6, 1, null, { normalOnly: true }], ...SHIKINE_BK, [K, 'gekka', 2, 5, 1, null, { skipNormal: true }]],
      objective: 'Destroy Zero’s unit before the Black Knights take the Kamine Ruins. Suzaku must survive.',
      win: { kill: ['zero'] },
      lose: { cmd: ['suzaku'], cities: ['Kamine Ruins'], turns: 15 },
      stars: [{ turns: 10 }, { keep: ['Shikine Base'] }],
      victory: 'Zero’s frame falls on Shikine. The Black Knights are leaderless, for now.',
      events: [
        {
          turn: 1,
          say: [
            ['suzaku', 'Zero is on this island. I will bring him in alive.'],
            ['zero', 'Come, Suzaku. Just a little closer.'],
          ],
        },
        {
          turn: 2,
          say: [[null, 'Gefjun Disturbers! The Lancelot and the frames around it lock up.']],
          stun: GEFJUN_TRAP,
        },
        {
          turn: 3,
          say: [['schneizel', 'Pull away from the Gefjun field. The bombardment will finish Zero.']],
          warn: { c: 4, r: 3, radius: 2, label: 'Bombardment' },
        },
        {
          turn: 4,
          say: [[null, 'Schneizel’s bombardment falls on the Black Knights’ position.']],
          blast: { c: 4, r: 3, damage: [0.8, 0.6, 0.4], color: '#ffb36b', name: 'Bombardment' },
        },
        {
          capture: 'Kamine Ruins',
          by: K,
          say: [['cc', 'The Gawain, unguarded. Zero, it’s ours.']],
          upgrade: { cmd: 'zero', type: 'elite_gawain' },
        },
      ],
    },
    {
      id: 'br_fukuoka',
      title: 'Battle of Fukuoka Base',
      place: 'Fukuoka Base, Kyushu',
      year: '2017 a.t.b.',
      brief:
        'Sawasaki and the Chinese Federation have taken Fukuoka and declared an independent Japan. Suzaku goes in first through the storm. Zero’s Gawain is out there too, and today it is aimed at the Federation.',
      unlock: 'Suzaku’s debt to Zero',
      player: B,
      sides: [B, K, 'cf'],
      teams: { bk: 'allies', britannia: 'allies', cf: 'sawasaki' },
      names: SAWASAKI,
      map: FUKUOKA,
      cities: FUKUOKA_CITIES,
      economy: { britannia: 300 },
      buildable: S1_BRIT,
      hold: { cf: 3 },
      units: [
        ...FUKUOKA_BRIT,
        [B, 'sutherland', 14, 11, 1, null, { normalOnly: true }],
        ...FUKUOKA_CF,
        ['cf', 'gun_ru', 6, 6, 1, null, { skipNormal: true }],
      ],
      objective: 'Destroy Sawasaki’s Federation army. Suzaku must survive.',
      win: { destroy: ['cf'] },
      lose: { cmd: ['suzaku'], turns: 14 },
      stars: [{ capture: ['Fukuoka Base'] }, { losses: 2 }],
      victory: 'Fukuoka Base is retaken. Suzaku never expected Zero to save his life.',
      events: [
        {
          turn: 1,
          say: [
            ['Sawasaki@cf', 'From Fukuoka, Japan is reborn, under the Federation’s protection.'],
            ['suzaku', 'Lancelot, landing. I’ll take Fukuoka back alone if I have to.'],
          ],
        },
        {
          turn: 3,
          say: [['zero', 'Suzaku. Today our enemy is the same. Don’t get in my way.']],
          spawn: FUKUOKA_BK,
        },
        FUKUOKA_REINFORCE,
      ],
    },
    {
      id: 'bk_pacific',
      title: 'Battle over the Pacific',
      place: 'Over the Pacific Ocean',
      year: '2018 a.t.b.',
      brief:
        'Nunnally, the new Viceroy of Area 11, flies in with an escort of Knights of the Round. Zero means to take her flagship in the air. The battlefield is the convoy’s sky: open air, cloud cover and a storm front.',
      unlock: 'Flight-enabled Akatsukis',
      player: K,
      sides: [K, B],
      map: PACIFIC,
      cities: PACIFIC_CITIES,
      economy: { bk: 400 },
      hold: { britannia: 3 },
      units: [...PACIFIC_BK, [K, 'akatsuki_flight', 1, 6, 1, null, { normalOnly: true }], ...PACIFIC_BRIT, [B, 'sutherland_air', 12, 6, 1, null, { skipNormal: true }]],
      objective: 'Capture the Governor’s Flagship. Zero must survive.',
      win: { capture: ['Governor’s Flagship'] },
      lose: { cmd: ['zero'], turns: 12 },
      stars: [{ kill: ['gino'] }, { losses: 2 }],
      victory: 'Zero reaches the flagship, but Nunnally will not leave with him. She means to revive the Special Administrative Zone.',
      events: [
        {
          turn: 1,
          say: [
            ['zero', 'Nunnally is aboard that flagship. Every unit, break through the escorts.'],
            ['suzaku', 'Knights of the Round, protect the Viceroy’s ship!'],
          ],
        },
        {
          turn: 3,
          say: [
            ['gino', 'So this is the famous Zero. Let’s see what you’ve got!'],
            ['anya', 'Target: the black frames. Firing.'],
          ],
        },
        {
          capture: 'Governor’s Flagship',
          by: K,
          say: [['Nunnally@britannia', 'Zero... I won’t go with you. I want to bring the Special Zone back.']],
        },
      ],
    },
    {
      id: 'bk_yokosuka2',
      title: 'Second Battle of Port Yokosuka',
      place: 'Tokyo Bay, off Port Yokosuka',
      year: '2018 a.t.b.',
      brief:
        'The Black Knights’ submarine is cornered in Tokyo Bay. Guilford’s warships ring the breakwater and their guns reach every hex of it. Zero needs only to survive long enough to bring the sea itself into the fight.',
      unlock: 'The road to One Million Zeros',
      player: K,
      sides: [K, B],
      map: TOKYO_BAY,
      cities: BAY_CITIES,
      economy: { bk: 300 },
      hold: { britannia: 1 },
      units: [
        ...BAY_BK,
        [K, 'akatsuki_flight', 9, 5, 1, null, { normalOnly: true }],
        ...BAY_BRIT,
        [B, 'sutherland', 4, 1, 1, null, { skipNormal: true }],
        [B, 'vincent_ward', 20, 1, 1, null, { skipNormal: true }],
      ],
      objective: 'Survive the encirclement, then board the Britannian Flagship. Zero must survive and the submarine must not fall.',
      win: { capture: ['Britannian Flagship'] },
      lose: { cmd: ['zero'], cities: ['Black Knights Submarine'], turns: 12 },
      stars: [{ kill: ['guilford'] }, { losses: 2 }],
      victory: 'Guilford’s fleet is scattered across Tokyo Bay, and the Black Knights slip out to sea.',
      events: [
        {
          turn: 1,
          say: [
            ['guilford', 'The submarine is trapped. Keep every gun on that breakwater.'],
            ['zero', 'Hold on. Britannia is about to learn how deep Tokyo Bay is.'],
          ],
        },
        {
          turn: 3,
          say: [
            ['zero', 'Torpedoes into the seabed. Now!'],
            [null, 'The seabed gives way. A wall of water capsizes the Britannian fleet.'],
          ],
          blast: WATER_WALL,
          shield: ['Destroyer North', 'Destroyer South', 'Destroyer East', 'Destroyer South-East', 'Britannian Flagship'].map(city => ({ city, value: 0 })),
          note: 'The fleet is crippled. Board the Britannian Flagship. Zero must survive.',
        },
      ],
    },
    {
      id: 'bk_xiaopei',
      title: 'Battle at Xiaopei',
      place: 'Xiaopei, Chinese Federation',
      year: '2018 a.t.b.',
      brief:
        'The Black Knights have taken the Tianzi from the Forbidden City and run for the Mausoleum of the Eighty-Eight Emperors. Li Xingke catches them at Xiaopei, and he has read every move Zero makes.',
      unlock: 'Lessons from defeat',
      player: K,
      sides: [K, 'cf'],
      names: FEDERATION,
      map: XIAOPEI,
      cities: [...XIAOPEI_CITIES, ['Mausoleum Road', 20, 6, K, 1]],
      economy: { bk: 300 },
      units: [
        ...XIAOPEI_BK,
        [K, 'akatsuki', 1, 5, 1, null, { normalOnly: true }],
        ...XIAOPEI_CF,
        ['cf', 'chuyen', 7, 2, 1, null, { skipNormal: true }],
        ['cf', 'gun_ru', 7, 10, 1, null, { skipNormal: true }],
      ],
      objective: 'Break through Xingke’s army to the Mausoleum Road. Zero must survive.',
      win: { reach: ['Mausoleum Road'] },
      lose: { cmd: ['zero'], turns: 12 },
      stars: [{ alive: ['tohdoh', 'ohgi'] }, { losses: 3 }],
      victory: 'The Black Knights reach the Mausoleum battered and without Kallen. Xingke is the first man to beat Zero in the field.',
      events: [
        {
          turn: 1,
          say: [
            ['xingke', 'Zero. You took the Tianzi from her palace. I have come to take her back.'],
            ['zero', 'Then come, Xingke. The road to the Mausoleum is ours.'],
          ],
        },
        {
          turn: 3,
          say: [['xingke', 'As I thought. Zero would make for the bridges. The guns are already on them.']],
          blast: { c: 8, r: 6, damage: [0.35, 0.25, 0.15], sides: [K], color: '#ffb36b', name: 'Federation barrage' },
        },
        { ...KALLEN_CAPTURED, note: 'Kallen has been captured. Break through to the Mausoleum Road. Zero must survive.' },
      ],
    },
    {
      id: 'bk_geass',
      title: 'Assault on the Geass Order',
      place: 'Geass Directorate, Chinese desert',
      year: '2018 a.t.b.',
      brief:
        'The Geass Directorate hides under the desert: the Order that made Geass, and V.V., who leads it. Zero brings the Black Knights, Rolo and Jeremiah to tear it out by the root.',
      unlock: 'Jeremiah joins Zero',
      player: K,
      sides: [K, 'neutral'],
      names: { neutral: { name: 'Geass Order', short: 'Geass Order', adj: 'Geass Order', color: '#b07ad6' } },
      map: GEASS,
      cities: [
        ['Strike Team Landing', 2, 6, K, 1],
        ['Directorate Gate', 7, 6, 'neutral', 1],
        ['Research Wing', 11, 2, 'neutral', 1],
        ['Archive Hall', 11, 10, 'neutral', 1],
        ['Directorate Core', 15, 6, 'neutral', 3, { fort: true, gun: 'Directorate Core' }],
      ],
      economy: { bk: 300 },
      hold: { neutral: 3 },
      units: [
        [K, 'elite_shinkiro', 2, 6, 1, 'zero'],
        [K, 'zangetsu', 3, 5, 1, 'tohdoh'],
        [K, 'sutherland', 3, 7, 1, 'jeremiah'],
        [K, 'vincent_commander', 2, 5, 1, 'rolo'],
        [K, 'akatsuki_zikisan', 4, 6, 1, 'chiba'],
        [K, 'akatsuki_zikisan', 2, 7, 1, 'asahina'],
        [K, 'akatsuki', 1, 6, 2, 'ohgi'],
        [K, 'akatsuki_missile', 1, 5, 1],
        [K, 'akatsuki', 1, 7, 1, null, { normalOnly: true }],
        ['neutral', 'vincent_ward', 7, 6, 2, null, { hold: 1 }],
        ['neutral', 'sutherland', 8, 4, 2, null, { hold: 2 }],
        ['neutral', 'sutherland', 8, 8, 2, null, { hold: 2 }],
        ['neutral', 'vincent_ward', 11, 2, 1, null, { hold: 1 }],
        ['neutral', 'vincent_ward', 11, 10, 1, null, { hold: 1 }],
        ['neutral', 'vincent_ward', 13, 5, 2],
        ['neutral', 'vincent_ward', 13, 7, 2],
        ['neutral', 'sutherland', 15, 6, 2, null, { hold: 1 }],
        ['neutral', 'gareth', 14, 4, 1],
        ['neutral', 'sutherland', 12, 6, 1, null, { skipNormal: true }],
        ['neutral', 'vincent_ward', 9, 6, 1, null, { skipNormal: true }],
      ],
      objective: 'Fight through the Directorate and capture its core. Zero must survive.',
      win: { capture: ['Directorate Core'] },
      lose: { cmd: ['zero'], turns: 14 },
      stars: [{ destroy: ['neutral'] }, { turns: 10 }],
      victory: 'The Geass Directorate is buried under the desert. V.V. has lost his Order.',
      events: [
        {
          turn: 1,
          say: [
            ['zero', 'The Geass Directorate is the root of all of it. Black Knights, erase it.'],
            ['jeremiah', 'V.V. made me what I am. Today I repay him.'],
          ],
        },
        {
          turn: 3,
          say: [
            ['V.V.@neutral', 'Lelouch. You really are just like your father.'],
            ['zero', 'The Siegfried. V.V. himself!'],
          ],
          spawn: [['neutral', 'siegfried', 15, 5, 1]],
        },
      ],
    },
    {
      id: 'br_pacific',
      title: 'Battle over the Pacific',
      place: 'Over the Pacific Ocean',
      year: '2018 a.t.b.',
      brief:
        'Nunnally flies to Area 11 as its new Viceroy, escorted by Suzaku, Gino and Anya. The Black Knights will strike in the air. The battlefield is the convoy’s sky: open air, cloud cover and a storm front.',
      unlock: 'Nunnally takes office',
      player: B,
      sides: [B, K],
      map: PACIFIC,
      cities: PACIFIC_CITIES,
      economy: { britannia: 400 },
      goals: { bk: [[20, 6, -6]] },
      units: [...PACIFIC_BRIT, [B, 'sutherland_air', 18, 8, 1, null, { normalOnly: true }], ...PACIFIC_BK, [K, 'akatsuki_flight', 1, 6, 1, null, { skipNormal: true }]],
      objective: 'Defend the Governor’s Flagship until the end of turn 9.',
      win: { hold: 9 },
      lose: { cities: ['Governor’s Flagship'] },
      stars: [{ kill: ['kallen'] }, { keep: ['Escort North', 'Escort South'] }],
      victory: 'The Black Knights break off over the Pacific. Nunnally lands safely in Area 11.',
      events: [
        {
          turn: 1,
          say: [
            ['suzaku', 'Knights of the Round, form up on the flagship. Zero must not reach the Viceroy.'],
            ['zero', 'Nunnally is aboard. Every unit, break through!'],
          ],
        },
        {
          turn: 3,
          say: [['gino', 'So this is the famous Zero. Anya, let’s give him a welcome!']],
        },
      ],
    },
    {
      id: 'br_yokosuka2',
      title: 'Second Battle of Port Yokosuka',
      place: 'Tokyo Bay, off Port Yokosuka',
      year: '2018 a.t.b.',
      brief:
        'Guilford’s fleet has the Black Knights’ submarine pinned against a breakwater in Tokyo Bay. Board it before Zero finds a way out.',
      unlock: 'Guilford’s vow',
      player: B,
      sides: [B, K],
      map: TOKYO_BAY,
      cities: BAY_CITIES,
      economy: { britannia: 400 },
      hold: { bk: 2 },
      units: [...BAY_BRIT, [B, 'vincent_ward', 4, 1, 1, null, { normalOnly: true }], ...BAY_BK, [K, 'akatsuki_flight', 9, 5, 1, null, { skipNormal: true }]],
      objective: 'Board the Black Knights’ submarine before they escape. Guilford must survive.',
      win: { capture: ['Black Knights Submarine'] },
      lose: { cmd: ['guilford'], cities: ['Britannian Flagship'], turns: 12 },
      stars: [{ kill: ['zero'] }, { losses: 3 }],
      victory: 'The submarine is taken. Zero has nowhere left to run in Tokyo Bay.',
      events: [
        {
          turn: 1,
          say: [
            ['guilford', 'Princess Cornelia, watch me. The Black Knights end here.'],
            ['zero', 'Hold on. Britannia is about to learn how deep Tokyo Bay is.'],
          ],
        },
        {
          turn: 4,
          say: [
            ['zero', 'Torpedoes into the seabed. Now!'],
            [null, 'A wall of water rolls through the bay and slams into the fleet.'],
          ],
          blast: WATER_WALL,
        },
      ],
    },
    {
      id: 'br_xiaopei',
      title: 'Intervention at Xiaopei',
      place: 'Xiaopei, Chinese Federation',
      year: '2018 a.t.b.',
      brief:
        'The Black Knights have stolen the Tianzi. Schneizel lends Li Xingke a Britannian detachment to block the road to the Mausoleum while the Federation army closes in from the west.',
      unlock: 'The Federation’s gratitude',
      player: B,
      sides: [B, 'cf', K],
      teams: { britannia: 'empire', cf: 'empire', bk: 'rebels' },
      names: FEDERATION,
      map: XIAOPEI,
      cities: [...XIAOPEI_CITIES, ['Mausoleum Road', 20, 6, B, 1]],
      economy: { britannia: 300 },
      goals: { bk: [[20, 6, -6]] },
      units: [
        [B, 'gareth', 20, 6, 1, 'schneizel'],
        [B, 'vincent_ward', 17, 5, 2],
        [B, 'vincent_ward', 17, 7, 2],
        [B, 'sutherland', 18, 3, 2],
        [B, 'sutherland', 18, 9, 2],
        [B, 'vincent_commander', 19, 6, 1],
        [B, 'vincent_ward', 20, 4, 1, null, { normalOnly: true }],
        ...XIAOPEI_CF,
        ...XIAOPEI_BK,
        [K, 'akatsuki', 1, 5, 1, null, { skipNormal: true }],
      ],
      objective: 'Destroy Zero’s unit before he reaches the Mausoleum Road. Schneizel must survive.',
      win: { kill: ['zero'] },
      lose: { cmd: ['schneizel'], cities: ['Mausoleum Road'], turns: 14 },
      stars: [{ kill: ['tohdoh'] }, { alive: ['xingke'] }],
      victory: 'Zero falls at Xiaopei. Schneizel has the Federation’s gratitude, and its debts.',
      events: [
        {
          turn: 1,
          say: [
            ['schneizel', 'The Federation asked for our help. Let us see how Zero fares against Li Xingke.'],
            ['xingke', 'Britannia’s help is not needed. But today I will not refuse it.'],
          ],
        },
        KALLEN_CAPTURED,
      ],
    },
    {
      id: 'br_mausoleum',
      title: 'The Mausoleum Campaign',
      place: 'Luoyang, Chinese Federation',
      year: '2018 a.t.b.',
      brief:
        'Zero has exposed the High Eunuchs’ bargain with Britannia, and Li Xingke has turned on them. Schneizel arrives to keep his new partners alive: hold the Vermillion Forbidden City against the Black Knights and Xingke.',
      unlock: 'Schneizel’s withdrawal',
      player: B,
      sides: [B, 'neutral', K, 'cf'],
      teams: { britannia: 'empire', neutral: 'empire', bk: 'rebels', cf: 'rebels' },
      names: EUNUCH_NAMES,
      map: LUOYANG,
      cities: LUOYANG_CITIES,
      economy: { britannia: 400 },
      hold: { neutral: 3 },
      goals: { bk: [[15, 4, -6]], cf: [[15, 4, -6]] },
      units: [
        [B, 'gareth', 21, 6, 1, 'schneizel'],
        [B, 'vincent_ward', 20, 5, 2],
        [B, 'vincent_ward', 20, 8, 2],
        [B, 'sutherland', 20, 3, 2],
        [B, 'sutherland', 20, 10, 1],
        [B, 'vincent_commander', 19, 6, 1],
        [B, 'vincent_ward', 21, 4, 1, null, { normalOnly: true }],
        ...LUOYANG_EUNUCHS,
        ...LUOYANG_REBELS.filter(u => u[0] === K),
        [K, 'akatsuki', 7, 11, 2, null, { skipNormal: true }],
        ...LUOYANG_REBELS.filter(u => u[0] === 'cf'),
      ],
      objective: 'Hold the Vermillion Forbidden City until the end of turn 10. Schneizel must survive.',
      win: { hold: 10 },
      lose: { cmd: ['schneizel'], cities: ['Vermillion Forbidden City'] },
      stars: [{ kill: ['xingke'] }, { keep: ['Eunuch Barracks'] }],
      victory: 'The Forbidden City holds, and the Eunuchs owe Britannia everything.',
      events: [
        {
          turn: 1,
          say: [
            ['schneizel', 'The Eunuchs offered us half the Federation. Let us make sure they live to sign it.'],
            ['xingke', 'They sold the Tianzi. I will not forgive them.'],
          ],
        },
        {
          turn: 5,
          say: [['guilford', 'Your Highness, my squadron is here. Where do you want us?']],
          spawn: [[B, 'gloucester', 21, 6, 2, 'guilford']],
        },
      ],
    },
    {
      id: 'bk8',
      title: 'Kagoshima Settlement',
      place: 'Kagoshima Settlement, Kyushu',
      year: '2018 a.t.b.',
      brief:
        'UFN Resolution Number One sends the Black Knights and the Federation ashore in southern Kyushu. Luciano Bradley’s Valkyrie Squadron holds Kagoshima, and the Knight of One is not far behind.',
      unlock: 'UFN mass production',
      player: K,
      sides: [K, 'cf', B],
      teams: { bk: 'ufn', cf: 'ufn', britannia: 'empire' },
      names: UFN,
      map: KAGOSHIMA,
      cities: KAGOSHIMA_CITIES,
      economy: { bk: 500, cf: 300 },
      industry: { bk: 200, cf: 120 },
      production: ['cf'],
      units: [
        ...KAGOSHIMA_BK,
        [K, 'akatsuki', 6, 10, 1, null, { normalOnly: true }],
        ...KAGOSHIMA_CF,
        ...KAGOSHIMA_BRIT,
        [B, 'vincent_ward', 3, 7, 1, null, { skipNormal: true }],
        [B, 'sutherland', 18, 8, 1, null, { skipNormal: true }],
      ],
      objective: 'Capture the Kagoshima Settlement. Tohdoh must survive.',
      win: { capture: ['Kagoshima Settlement'] },
      lose: { cmd: ['tohdoh'], turns: 16 },
      stars: [{ kill: ['luciano'] }, { alive: ['xingke'] }],
      victory: 'Kagoshima falls to the UFN. The Valkyrie Squadron is broken, and Japan’s liberation has begun.',
      events: [
        {
          turn: 1,
          say: [
            ['tohdoh', 'UFN Resolution Number One is in force. Black Knights, take Kagoshima.'],
            ['xingke', 'The Federation lands in the east. We will meet you in the settlement.'],
            ['luciano', 'Valkyries! Let’s find out how loud these UFN pilots scream.'],
          ],
        },
        {
          turn: 4,
          say: [
            ['bismarck', 'Li Xingke. The Knight of One will be your opponent.'],
            ['xingke', 'The Knight of One... Then the Shen Hu will give you the Federation’s answer.'],
          ],
          spawn: [[B, 'brighton', 13, 2, 1, 'bismarck']],
        },
      ],
    },
    {
      id: 'br_kagoshima',
      title: 'Kagoshima Settlement',
      place: 'Kagoshima Settlement, Kyushu',
      year: '2018 a.t.b.',
      brief:
        'The UFN has landed in southern Kyushu. The Knight of One and Luciano Bradley’s Valkyrie Squadron must hold Kagoshima until the counterattack is ready.',
      unlock: 'The Knight of One’s stand',
      player: B,
      sides: [B, K, 'cf'],
      teams: { bk: 'ufn', cf: 'ufn', britannia: 'empire' },
      names: UFN,
      map: KAGOSHIMA,
      cities: KAGOSHIMA_CITIES,
      economy: { britannia: 500, bk: 300, cf: 300 },
      industry: { britannia: 200, bk: 120, cf: 120 },
      production: [K, 'cf'],
      goals: { bk: [[6, 5, -6]], cf: [[6, 5, -6]] },
      units: [
        ...KAGOSHIMA_BRIT,
        [B, 'brighton', 13, 2, 1, 'bismarck'],
        [B, 'vincent_ward', 9, 4, 1, null, { normalOnly: true }],
        ...KAGOSHIMA_BK,
        [K, 'akatsuki', 6, 10, 1, null, { skipNormal: true }],
        ...KAGOSHIMA_CF,
      ],
      objective: 'Hold the Kagoshima Settlement until the end of turn 10. Bismarck must survive.',
      win: { hold: 10 },
      lose: { cmd: ['bismarck'], cities: ['Kagoshima Settlement'] },
      stars: [{ kill: ['xingke'] }, { alive: ['luciano'] }],
      victory: 'The UFN landing stalls on Kyushu’s beaches. The Knight of One has held the south.',
      events: [
        {
          turn: 1,
          say: [
            ['bismarck', 'The UFN has come ashore. Kagoshima holds until I say otherwise.'],
            ['luciano', 'Valkyries! Let’s find out how loud these UFN pilots scream.'],
          ],
        },
        {
          turn: 3,
          say: [['kallen', 'Luciano Bradley. I have been waiting for you.']],
        },
      ],
    },
  ];

