  const EUROPE = [
    // ======== Euro Britannia ========
    {
      id: 'eb_narva',
      title: 'Battle of Narva',
      place: 'Narva, Estonia',
      year: '2017 a.t.b.',
      brief:
        'The E.U.’s 132nd Regiment failed to retake Sankt Petersburg and is running west. Andrea Farnese’s Knights of St. Raphael have it trapped in the forests of Narva, but strange new E.U. frames are coming to cover the retreat.',
      unlock: 'The legend of Hannibal’s Ghost',
      player: EB,
      sides: [EB, 'eu'],
      map: NARVA,
      cities: NARVA_CITIES,
      economy: { eb: 300 },
      hold: { eu: 2 },
      units: [...NARVA_EB, [EB, 'gloucester', 18, 5, 1, null, { normalOnly: true }], ...NARVA_EU, ['eu', 'alexander', 2, 11, 1, null, { skipNormal: true }]],
      objective: 'Cut off the 132nd Regiment Column. Farnese and his G-1 must survive.',
      win: { capture: ['132nd Regiment Column'] },
      lose: { cmd: ['farnese'], cities: ['Euro-Britannian G-1'], turns: 14 },
      stars: [{ kill: ['akito'] }, { losses: 3 }],
      victory: 'The 132nd Regiment is cut off at Narva. Euro Britannia’s grip on Sankt Petersburg is safe.',
      events: [
        {
          turn: 1,
          say: [
            ['farnese', 'The 132nd runs from Sankt Petersburg. Close the road at Narva; let none of them reach the border.'],
            ['leila', 'wZERO, cover the 132nd’s withdrawal. Buy them every minute you can.'],
          ],
        },
        {
          turn: 3,
          say: [
            [null, 'The Alexanders drop into insect form and charge through the trees. Their pilots fight as if they mean to die.'],
            ['farnese', 'Hold your positions! We know nothing about these frames.'],
          ],
        },
        NARVA_MANFREDI,
      ],
    },
    {
      id: 'eb_slonim',
      title: 'Battle of Slonim',
      place: 'Slonim, Belarus',
      year: '2017 a.t.b.',
      brief:
        'wZERO has dropped from orbit behind the lines near Slonim to break the front open. Ashley Ashra’s Asura Strike Force of the Knights of St. Michael hunts the landing party, and the new Grand Master, Shin Hyuga Shaing, watches from his G-1.',
      unlock: 'Shin’s Vercingetorix',
      player: EB,
      sides: [EB, 'eu'],
      map: SLONIM,
      cities: SLONIM_CITIES,
      economy: { eb: 300 },
      goals: { eu: [[12, 4, -6]] },
      units: [...SLONIM_EB, [EB, 'gloucester', 16, 7, 1, null, { normalOnly: true }], ...SLONIM_EU, ['eu', 'alexander_drone', 19, 10, 1, null, { skipNormal: true }]],
      objective: 'Destroy the wZERO landing force. Ashley must survive and Slonim must not fall.',
      win: { destroy: ['eu'] },
      lose: { cmd: ['ashley'], cities: ['Slonim'], turns: 14 },
      stars: [{ kill: ['leila'] }, { keep: ['Long-Range Cannon North', 'Long-Range Cannon South'] }],
      victory: 'The wZERO landing is wiped out in the Slonim forest. Shin has found his brother, and lost nothing.',
      events: [
        {
          turn: 1,
          say: [
            ['ashley', 'Hannibal’s Ghosts dropped right into our forest. Asura Strike Force, hunt them down!'],
            ['Johanne@eb', 'Captain, the cannons have their landing zone.'],
          ],
        },
        SLONIM_BARRAGE,
        SLONIM_SHIN,
      ],
    },
    {
      id: 'br6',
      title: 'European Front',
      place: 'Euro Britannia, the eastern front',
      year: '2017 a.t.b.',
      brief:
        'Julius Kingsley’s Ark Fleet has Paris in a panic and the E.U. front is falling back. He orders Euro Britannia forward on every front at once: Shin leads the Knights of St. Michael into the gap. Take Warsaw.',
      unlock: 'Kingsley’s offensive',
      player: EB,
      sides: [EB, 'eu'],
      map: EASTERN_FRONT,
      cities: EASTERN_CITIES,
      economy: { eb: 500, eu: 500 },
      industry: { eb: 200, eu: 200 },
      production: ['eu'],
      units: [
        ...EASTERN_EB,
        [EB, 'gracchus', 20, 12, 1, null, { normalOnly: true }],
        ...EASTERN_EU,
        ['eu', 'gardmare', 14, 9, 1, null, { skipNormal: true }],
        ['eu', 'alexander_drone', 15, 10, 2, null, { skipNormal: true }],
      ],
      objective: 'Capture Warsaw. Moscow must hold.',
      win: { capture: ['Warsaw'] },
      lose: { cities: ['Moscow'], turns: 22 },
      stars: [{ kill: ['akito'] }, { capture: ['Smolensk', 'Minsk', 'Vilnius', 'Warsaw'] }],
      victory: 'Warsaw falls. The E.U.’s eastern front collapses before Euro Britannia.',
      events: [
        {
          turn: 1,
          say: [
            ['augustus', 'Euro Britannia marches west. Bring me Warsaw.'],
            ['julius', 'The E.U. is a carcass waiting to fall. Shin, take the center; Ashley, the south.'],
            ['shin', 'And the Alexanders? I would very much like to meet their pilot.'],
            ['leila', 'wZERO, hold the line at Minsk. We fight smarter than they do.'],
          ],
        },
      ],
    },
    {
      id: 'eb_petersburg',
      title: 'Coup at Sankt Petersburg',
      place: 'Sankt Petersburg, Euro Britannia',
      year: '2017 a.t.b.',
      brief:
        'Shin has seen through Julius Kingsley: Zero’s tactics in a Britannian uniform, and a prince of the Empire under the eyepatch. The Knights of St. Michael move on Caesar’s Palace, and the Knight of Seven stands in their way.',
      unlock: 'Shin rules Euro Britannia',
      player: EB,
      sides: [EB, B],
      map: PETERSBURG,
      cities: [
        ['St. Michael Barracks', 2, 3, EB, 2],
        ['Neva Embankment', 8, 6, EB, 1],
        ['Caesar’s Palace', 17, 4, B, 3],
        ['Admiralty', 15, 7, B, 1],
        ['Imperial Station', 17, 10, B, 1],
      ],
      economy: { eb: 300 },
      hold: { britannia: 2 },
      units: [
        [EB, 'vercingetorix', 3, 4, 1, 'shin'],
        [EB, 'gloucester', 2, 5, 2],
        [EB, 'gracchus', 4, 6, 2],
        [EB, 'gracchus', 3, 7, 2],
        [EB, 'sutherland', 5, 3, 2],
        [EB, 'sutherland', 4, 9, 2],
        [EB, 'liverpool', 1, 6, 1],
        [EB, 'gloucester', 2, 7, 1, null, { normalOnly: true }],
        [B, 'elite_lancelot', 16, 5, 1, 'suzaku', { hold: false }],
        [B, 'gloucester', 17, 4, 1, 'julius', { hold: 1 }],
        [B, 'sutherland', 14, 3, 2],
        [B, 'sutherland', 14, 7, 2],
        [B, 'sutherland', 16, 8, 2],
        [B, 'gloucester', 18, 6, 2],
        [B, 'sutherland', 17, 10, 1, null, { hold: 1 }],
        [B, 'sutherland', 13, 5, 1, null, { skipNormal: true }],
        [B, 'gloucester', 19, 3, 1, null, { skipNormal: true }],
      ],
      objective: 'Capture Caesar’s Palace. Shin must survive.',
      win: { capture: ['Caesar’s Palace'] },
      lose: { cmd: ['shin'], turns: 12 },
      stars: [
        { kill: ['suzaku'], text: 'Bring down the Lancelot' },
        { kill: ['julius'], text: 'Take Julius Kingsley' },
      ],
      victory: 'Caesar’s Palace is Shin’s. Kingsley and the Knight of Seven vanish into his cells, and Euro Britannia answers to St. Michael.',
      events: [
        {
          turn: 1,
          say: [
            ['shin', 'Kingsley plays Zero’s game with Zero’s moves. Knights of St. Michael, take the palace.'],
            ['julius', 'Kamine Island... Nunnally? Where is Nunnally?'],
            ['suzaku', 'Any knight who raises a hand against Sir Kingsley is a traitor to the Emperor.'],
          ],
        },
        {
          turn: 3,
          say: [['Jean@eb', 'Shin-sama, the Knights of St. Michael are with you to the last.']],
        },
      ],
    },
    {
      id: 'eb_ark',
      title: 'The Gallia Grande',
      place: 'The Gallia Grande, over the North Sea',
      year: '2017 a.t.b.',
      brief:
        'The Ark Fleet was a bluff: the Gallia Grande is unarmed. wZERO has boarded it to prove it. Ashley Ashra and his new Ahura Mazda must throw them off the ship, and Shin has left something aboard that Ashley does not know about.',
      unlock: 'Ahura Mazda',
      player: EB,
      sides: [EB, 'eu'],
      map: GALLIA,
      cities: ARK_CITIES,
      economy: { eb: 200 },
      hold: { eu: 2 },
      units: [...ARK_EB, [EB, 'sutherland', 14, 3, 1, null, { normalOnly: true }], ...ARK_EU, ['eu', 'alexander', 1, 4, 1, null, { skipNormal: true }]],
      objective: 'Destroy the wZERO boarding party. Ashley must survive and the bridge must not fall.',
      win: { destroy: ['eu'] },
      lose: { cmd: ['ashley'], cities: ['Gallia Grande Bridge'], turns: 9 },
      stars: [{ kill: ['akito'] }, { turns: 4, text: 'Win before the time bombs go off' }],
      victory: 'The boarders are dead. Ashley will soon learn what Shin left in the hold.',
      events: [
        {
          turn: 1,
          say: [
            ['ashley', 'Hannibal’s Ghost, on my ship. This time you don’t walk away.'],
            ['akito', 'The Ark is empty. Ryo, Ayano, Yukiya: the bridge.'],
          ],
        },
        ARK_WARNING,
        ARK_BLAST,
      ],
    },
    {
      id: 'eb_weisswolf',
      title: 'Siege of Castle Weisswolf',
      place: 'Castle Weisswolf',
      year: '2017 a.t.b.',
      brief:
        'The Knights of St. Michael have found wZERO’s base. Shin means to take Castle Weisswolf and its Apollo’s Chariot missiles, and with them, strike Pendragon itself. A minefield and a wall stand in the way.',
      unlock: 'Apollo’s Chariot',
      player: EB,
      sides: [EB, 'eu'],
      map: WEISSWOLF,
      cities: WEISSWOLF_CITIES,
      economy: { eb: 400 },
      industry: { eb: 150 },
      buildable: { eb: ['sutherland', 'gloucester', 'gracchus', 'liverpool'] },
      hold: { eu: 2 },
      units: [...SIEGE_EB, [EB, 'gloucester', 2, 8, 1, null, { normalOnly: true }], ...SIEGE_EU, ['eu', 'estrella', 12, 9, 1, null, { skipNormal: true }], ['eu', 'alexander_drone', 11, 9, 1, null, { skipNormal: true }]],
      objective: 'Capture the Outer Defense Line and Apollo’s Chariot Silo. Shin must survive.',
      win: { capture: ['Outer Defense Line', 'Apollo’s Chariot Silo'] },
      lose: { cmd: ['shin'], turns: 14 },
      stars: [{ capture: ['Castle Weisswolf'] }, { losses: 4 }],
      victory: 'Apollo’s Chariot is in Shin’s hands. Castle Weisswolf will not hold much longer.',
      events: [
        {
          turn: 1,
          say: [
            ['shin', 'Castle Weisswolf. Break the wall, and Apollo’s Chariot is ours.'],
            ['leila', 'Everyone to the walls. The minefield will buy us time.'],
          ],
        },
        ...SIEGE_EVENTS,
      ],
    },
    {
      id: 'eb_assault',
      title: 'Assault on Castle Weisswolf',
      place: 'Castle Weisswolf',
      year: '2017 a.t.b.',
      brief:
        'Yukiya’s bomb cost the Knights of St. Michael two thirds of their strength, but Shin’s Geass will not let them stop. Take Castle Weisswolf. Akito is waiting for his brother.',
      unlock: 'The end of the Shaing line',
      player: EB,
      sides: [EB, 'eu'],
      map: WEISSWOLF,
      cities: ASSAULT_CITIES,
      economy: { eb: 300 },
      hold: { eu: 2 },
      units: [...ASSAULT_EB, [EB, 'sutherland', 6, 7, 1, null, { normalOnly: true }], ...ASSAULT_EU, ['eu', 'alexander_drone', 14, 9, 1, null, { skipNormal: true }]],
      objective: 'Capture Castle Weisswolf. Shin must survive.',
      win: { capture: ['Castle Weisswolf'] },
      lose: { cmd: ['shin'], turns: 14 },
      stars: [{ kill: ['akito'] }, { kill: ['ashley'], text: 'Destroy the traitor Ashley' }],
      victory: 'Castle Weisswolf falls, and Apollo’s Chariot turns toward Pendragon.',
      events: [
        ASSAULT_OPENING,
        {
          turn: 5,
          say: [
            ['Jean@eb', 'For you, Shin-sama!'],
            [null, 'Jean Rowe’s bomb goes off inside the castle walls.'],
          ],
          blast: { c: 16, r: 6, damage: [0.5, 0.3], sides: ['eu'], color: '#ffb36b', name: 'Jean’s bomb' },
        },
      ],
    },
    {
      id: 'eb_fall',
      title: 'The Fall of Europia',
      place: 'Paris',
      year: '2018 a.t.b.',
      brief:
        'Smilas’s coup split the E.U. in two, and the Republic never recovered. A year later Schneizel’s armies and Euro Britannia’s knights march on Paris together to end the war in the West.',
      unlock: 'Europe under the Empire',
      player: EB,
      sides: [EB, B, 'eu'],
      teams: { eb: 'empire', britannia: 'empire', eu: 'europia' },
      map: PARIS,
      cities: PARIS_CITIES({ north: 'eu', palace: 'eu', east: 'eu', landing: EB }),
      economy: { eb: 500 },
      industry: { eb: 200 },
      units: [
        [EB, 'gloucester', 3, 10, 2, 'farnese'],
        [EB, 'sutherland', 4, 11, 2, 'augustus'],
        [EB, 'gracchus', 2, 9, 2, 'kewell'],
        [EB, 'gloucester', 5, 10, 2],
        [EB, 'canterbury', 3, 12, 1],
        [EB, 'liverpool', 2, 11, 1],
        [EB, 'gloucester', 1, 9, 1, null, { normalOnly: true }],
        [B, 'gareth', 20, 8, 1, 'schneizel'],
        [B, 'vincent_ward', 19, 7, 2],
        [B, 'vincent_ward', 20, 10, 2],
        [B, 'vincent_ward', 19, 11, 1],
        ['eu', 'estrella', 12, 3, 2, 'oscar', { hold: 1 }],
        ['eu', 'panzer_wespe', 7, 7, 1, 'fernando', { hold: 1 }],
        ['eu', 'estrella', 15, 1, 1, 'marirrosa', { hold: 1 }],
        ['eu', 'panzer_hummel', 11, 2, 1, null, { hold: 1 }],
        ['eu', 'panzer_hummel', 13, 2, 1, null, { hold: 1 }],
        ['eu', 'hummel_battery', 12, 4, 1, null, { hold: 1 }],
        ['eu', 'gardmare', 9, 6, 1],
        ['eu', 'gardmare', 15, 6, 1],
        ['eu', 'alexander_mp', 10, 4, 2],
        ['eu', 'estrella', 18, 9, 1, null, { hold: 1 }],
        ['eu', 'estrella', 8, 3, 1, null, { skipNormal: true }],
        ['eu', 'alexander_drone', 14, 7, 1, null, { skipNormal: true }],
      ],
      objective: 'Capture the Élysée Palace. Farnese must survive.',
      win: { capture: ['Élysée Palace'] },
      lose: { cmd: ['farnese'], turns: 16 },
      stars: [{ capture: ['Gare du Nord', 'Les Invalides', 'Bois de Vincennes'] }, { turns: 11 }],
      victory: 'The Élysée flies Britannia’s colors. The Europia United is finished as a world power.',
      events: [
        {
          turn: 1,
          say: [
            ['augustus', 'Smilas tore the Republic in two. Euro Britannia finishes what Kingsley began.'],
            ['schneizel', 'Britannia marches with you. Let Europia sign its surrender in Paris.'],
            ['oscar', 'Hold Paris! The Republic does not kneel.'],
          ],
        },
        {
          turn: 5,
          say: [['fernando', 'Reserves from the south are here. Push them back across the Seine!']],
          spawn: [
            ['eu', 'estrella', 12, 0, 2],
            ['eu', 'alexander_mp', 8, 0, 1],
          ],
        },
      ],
    },
    // ======== The E.U. (wZERO) ========
    {
      id: 'eu_narva',
      title: 'Battle of Narva',
      place: 'Narva, Estonia',
      year: '2017 a.t.b.',
      brief:
        'The 132nd Regiment’s attack on Sankt Petersburg has failed and Euro Britannia is closing in on its retreat. wZERO’s Japanese pilots and their Alexanders are sent to cover the withdrawal. Leila Malcal has just taken command.',
      unlock: 'Hannibal’s Ghost',
      player: 'eu',
      sides: ['eu', EB],
      map: NARVA,
      cities: NARVA_CITIES,
      economy: { eu: 300 },
      goals: { eb: [[3, 1, -6]] },
      units: [...NARVA_EU, ['eu', 'alexander', 4, 8, 1, null, { normalOnly: true }], ...NARVA_EB, [EB, 'sutherland', 11, 6, 1, null, { skipNormal: true }], [EB, 'glasgow', 16, 10, 1, null, { skipNormal: true }]],
      objective: 'Protect the 132nd Regiment Column until the end of turn 8.',
      win: { hold: 8 },
      lose: { cities: ['132nd Regiment Column'] },
      stars: [{ capture: ['Euro-Britannian G-1'] }, { alive: ['akito'] }],
      victory: 'The 132nd Regiment gets away. Akito Hyuga walks out of the forest alone, and Euro Britannia starts talking about a ghost.',
      events: [
        {
          turn: 1,
          say: [
            ['leila', 'wZERO, cover the 132nd’s withdrawal. And disarm the self-destruct systems. Nobody dies for a bomb today.'],
            ['akito', '...Understood.'],
          ],
        },
        {
          turn: 3,
          say: [['farnese', 'These frames... Hold back! We know nothing about what we are fighting.']],
        },
        NARVA_MANFREDI,
      ],
    },
    {
      id: 'eu_ambush',
      title: 'Ryo’s Ambush',
      place: 'The road to Weisswolf',
      year: '2017 a.t.b.',
      brief:
        'General Smilas’s convoy follows its GPS onto a land bridge rigged with explosives. Ryo Sayama and his gang want a hostage and the E.U.’s newest frames. Akito is trapped on the far side with only a Gardmare.',
      unlock: 'Ryo, Ayano and Yukiya join wZERO',
      player: 'eu',
      sides: ['eu', 'neutral'],
      names: { neutral: { name: 'Ryo’s Gang', short: 'Ryo’s Gang', adj: 'Gang', color: '#c98a4a' } },
      map: RAVINE,
      cities: [
        ['EU Convoy', 2, 5, 'eu', 1],
        ['Ryo’s Hideout', 15, 5, 'neutral', 1],
      ],
      economy: { eu: 150 },
      units: [
        ['eu', 'gardmare', 9, 5, 1, 'akito'],
        ['eu', 'gardmare', 6, 5, 1],
        ['eu', 'gardmare', 4, 4, 1],
        ['eu', 'estrella', 3, 6, 1],
        ['eu', 'gardmare', 3, 4, 1, null, { normalOnly: true }],
        ['neutral', 'glasgow', 13, 5, 1, 'ryo'],
        ['neutral', 'glasgow', 12, 3, 1, 'ayano'],
        ['neutral', 'glasgow', 12, 7, 1, 'yukiya'],
        ['neutral', 'sutherland', 15, 4, 1],
        ['neutral', 'glasgow', 14, 6, 1, null, { skipNormal: true }],
      ],
      objective: 'Disable Ryo’s Glasgow. Akito must survive and the convoy must not fall.',
      win: { kill: ['ryo'] },
      lose: { cmd: ['akito'], cities: ['EU Convoy'], turns: 10 },
      stars: [{ turns: 6 }, { losses: 1 }],
      victory: 'Ryo’s Glasgow is crippled. Leila offers the three of them what they wanted most: a place to belong.',
      events: [
        {
          turn: 1,
          say: [
            ['ryo', 'They drove straight onto the bridge. Yukiya, now!'],
            [null, 'The land bridge collapses. Akito is cut off on the far side.'],
          ],
          blast: { c: 7, r: 5, damage: [0.6, 0.4], sides: ['eu'], terrain: 'peak', terrainRadius: 0, color: '#b08a5a', name: 'Bridge charge' },
        },
        {
          turn: 5,
          say: [['smilas', 'Air support is here. It’s over, boy.']],
          spawn: [
            ['eu', 'estrella', 16, 1, 1],
            ['eu', 'estrella', 16, 9, 1],
          ],
        },
        {
          killed: 'ryo',
          say: [['ryo', '...Fine. If it means a place where we belong, we’ll fly your frames.']],
        },
      ],
    },
    {
      id: 'eu_slonim',
      title: 'Battle of Slonim',
      place: 'Slonim, Belarus',
      year: '2017 a.t.b.',
      brief:
        'wZERO drops from orbit behind the lines between Lyakhavichy and Nyasvizh to break the front for the push on Warsaw. For the first time Leila goes into the field herself. Ashley Ashra’s knights are already waiting.',
      unlock: 'Slonim reclaimed',
      player: 'eu',
      sides: ['eu', EB],
      map: SLONIM,
      cities: SLONIM_CITIES,
      economy: { eu: 200 },
      units: [...SLONIM_EU, ['eu', 'alexander_drone', 19, 10, 1, null, { normalOnly: true }], ...SLONIM_EB, [EB, 'gloucester', 16, 7, 1, null, { skipNormal: true }], [EB, 'liverpool', 15, 10, 1, null, { skipNormal: true }]],
      objective: 'Capture Slonim. Leila must survive.',
      win: { capture: ['Slonim'] },
      lose: { cmd: ['leila'], turns: 14 },
      stars: [{ capture: ['Long-Range Cannon North', 'Long-Range Cannon South'] }, { alive: ['akito', 'ryo', 'ayano', 'yukiya'] }],
      victory: 'Slonim is back in E.U. hands, and the front moves east. Akito has met his brother again.',
      events: [
        {
          turn: 1,
          say: [
            ['leila', 'This is my first time in the field. wZERO, the long-range cannons first.'],
            ['ashley', 'Hannibal’s Ghosts! Asura Strike Force, hunt them down!'],
          ],
        },
        SLONIM_BARRAGE,
        SLONIM_SHIN,
      ],
    },
    {
      id: 'eu_front',
      title: 'Defense of Warsaw',
      place: 'The eastern front, Warsaw',
      year: '2017 a.t.b.',
      brief:
        'Kingsley’s Ark Fleet has Paris rioting and the E.U. front pulling back. wZERO, stripped of its credentials and stuck in Warsaw, is all that stands between Euro Britannia’s offensive and the city.',
      unlock: 'The Wyvern holds',
      player: 'eu',
      sides: ['eu', EB],
      map: EASTERN_FRONT,
      cities: EASTERN_CITIES,
      economy: { eu: 500, eb: 500 },
      industry: { eu: 200, eb: 200 },
      production: [EB],
      goals: { eb: [[2, 7, -6]] },
      units: [
        ...EASTERN_EU,
        ['eu', 'estrella', 4, 8, 1, null, { normalOnly: true }],
        ...EASTERN_EB,
        [EB, 'gracchus', 19, 4, 1, null, { skipNormal: true }],
        [EB, 'sutherland', 21, 11, 1, null, { skipNormal: true }],
      ],
      objective: 'Hold Warsaw until the end of turn 12.',
      win: { hold: 12 },
      lose: { cities: ['Warsaw'] },
      stars: [{ keep: ['Vilnius', 'Minsk'] }, { kill: ['ashley'] }],
      victory: 'Euro Britannia’s offensive breaks on Warsaw. The Ark Fleet was never real, and now Paris knows it.',
      events: [
        {
          turn: 1,
          say: [
            ['leila', 'The Ark Fleet scare has the whole front running. wZERO holds Warsaw, alone if we must.'],
            ['julius', 'All fronts, advance. The E.U. collapses the moment it stops believing in itself.'],
            ['shin', 'And the Alexanders? I would very much like to meet their pilot.'],
          ],
        },
      ],
    },
    {
      id: 'eu_ark',
      title: 'The Gallia Grande',
      place: 'The Gallia Grande, over the North Sea',
      year: '2017 a.t.b.',
      brief:
        'The Ark Fleet that terrifies Paris is a single ship, and it carries no bombs. Akito, Ryo, Ayano and Yukiya board the Gallia Grande to prove it. Ashley Ashra is waiting on deck in a new frame.',
      unlock: 'Ashley Ashra’s respect',
      player: 'eu',
      sides: ['eu', EB],
      map: GALLIA,
      cities: ARK_CITIES,
      economy: { eu: 150 },
      hold: { eb: 2 },
      units: [...ARK_EU, ['eu', 'alexander', 1, 4, 1, null, { normalOnly: true }], ...ARK_EB, [EB, 'sutherland', 10, 3, 1, null, { skipNormal: true }], [EB, 'sutherland', 10, 8, 1, null, { skipNormal: true }]],
      objective: 'Take the Gallia Grande’s bridge. Akito must survive.',
      win: { capture: ['Gallia Grande Bridge'] },
      lose: { cmd: ['akito'], turns: 10 },
      stars: [{ alive: ['ashley'], text: 'Spare Ashley: his Ahura Mazda survives' }, { losses: 1 }],
      victory: 'The bridge is taken and the Ark’s secret is out. Ashley Ashra, betrayed by Shin, chooses a new side.',
      events: [
        {
          turn: 1,
          say: [
            ['leila', 'The Ark is unarmed. Find out what it really is, and bring everyone home.'],
            ['ashley', 'Hannibal’s Ghost. This time you don’t walk away.'],
          ],
        },
        ARK_WARNING,
        ARK_BLAST,
      ],
    },
    {
      id: 'eu_weisswolf',
      title: 'Siege of Castle Weisswolf',
      place: 'Castle Weisswolf',
      year: '2017 a.t.b.',
      brief:
        'The Knights of St. Michael have found Castle Weisswolf. Shin wants its Apollo’s Chariot missiles to strike Pendragon, and the pilots are still missing after the Gallia Grande. Hold the castle until they come back.',
      unlock: 'The last line',
      player: 'eu',
      sides: ['eu', EB],
      map: WEISSWOLF,
      cities: WEISSWOLF_CITIES,
      economy: { eu: 300 },
      industry: { eu: 120 },
      goals: { eb: [[17, 3, -6], [17, 6, -4]] },
      units: [...SIEGE_EU, ['eu', 'estrella', 14, 6, 1, null, { normalOnly: true }], ...SIEGE_EB, [EB, 'sutherland', 3, 9, 1, null, { skipNormal: true }], [EB, 'gloucester', 2, 3, 1, null, { skipNormal: true }]],
      objective: 'Hold Castle Weisswolf until the end of turn 10. Leila must survive.',
      win: { hold: 10 },
      lose: { cmd: ['leila'], cities: ['Castle Weisswolf'] },
      stars: [{ keep: ['Apollo’s Chariot Silo'] }, { losses: 3 }],
      victory: 'The Knights of St. Michael fall back from the walls, a third of what they were. Shin will come again.',
      events: [
        {
          turn: 1,
          say: [
            ['leila', 'Everyone to the walls. The minefield will buy us time.'],
            ['shin', 'Castle Weisswolf. Break the wall, and Apollo’s Chariot is ours.'],
          ],
        },
        ...SIEGE_EVENTS,
      ],
    },
    {
      id: 'eu_assault',
      title: 'Assault on Castle Weisswolf',
      place: 'Castle Weisswolf',
      year: '2017 a.t.b.',
      brief:
        'Shin’s Geass has gone out of control and his knights come on regardless. Ashley Ashra now fights for wZERO in the Alexander Red Ogre. Akito cuts his hair and gives it to Leila before he goes out to face his brother.',
      unlock: 'Alexander Liberte',
      player: 'eu',
      sides: ['eu', EB],
      map: WEISSWOLF,
      cities: ASSAULT_CITIES,
      economy: { eu: 300 },
      units: [...ASSAULT_EU, ['eu', 'alexander_drone', 14, 9, 1, null, { normalOnly: true }], ...ASSAULT_EB, [EB, 'sutherland', 6, 7, 1, null, { skipNormal: true }]],
      objective: 'Destroy Shin’s Vercingetorix. Akito must survive and the castle must not fall.',
      win: { kill: ['shin'] },
      lose: { cmd: ['akito'], cities: ['Castle Weisswolf'], turns: 14 },
      stars: [{ capture: ['Jean’s Bomb Site'], text: 'Stop Jean’s bomb' }, { alive: ['ryo', 'ayano', 'yukiya', 'ashley'] }],
      victory: 'Shin falls at Castle Weisswolf, and in the end he asks his brother to live. wZERO lays down its arms and goes home to the Roma.',
      events: [
        ASSAULT_OPENING,
        {
          capture: 'Jean’s Bomb Site',
          by: 'eu',
          say: [['ayano', 'Got her! That bomb isn’t going off.']],
        },
        {
          killed: 'shin',
          say: [['shin', 'You’re not alone, Akito. Live. Keep living.']],
        },
      ],
    },
    {
      id: 'eu_paris',
      title: 'Smilas’s Coup',
      place: 'Paris',
      year: '2017 a.t.b.',
      brief:
        'General Smilas used Leila as a symbol and now reaches for a crown: he means to rule Europe. Ashley Ashra’s Asura Strike Force stands against his faction in Paris until their captain arrives.',
      unlock: 'A Republic, divided',
      player: 'eu',
      sides: ['eu', 'neutral'],
      names: { neutral: { name: 'Smilas Faction', short: 'Smilas', adj: 'Smilas', color: '#78a8a0' } },
      map: PARIS,
      cities: PARIS_CITIES({ north: 'neutral', palace: 'neutral', east: 'eu', landing: 'eu' }),
      economy: { eu: 300 },
      hold: { neutral: 2 },
      units: [
        ['eu', 'gloucester', 3, 10, 2],
        ['eu', 'gloucester', 4, 11, 2],
        ['eu', 'gloucester', 2, 9, 2],
        ['eu', 'estrella', 18, 9, 2],
        ['eu', 'gardmare', 17, 10, 1],
        ['eu', 'estrella', 3, 9, 1, null, { normalOnly: true }],
        ['neutral', 'panzer_wespe', 12, 3, 1, 'smilas', { hold: 1 }],
        ['neutral', 'estrella', 10, 4, 2],
        ['neutral', 'estrella', 14, 4, 2],
        ['neutral', 'estrella', 11, 6, 2],
        ['neutral', 'panzer_hummel', 12, 2, 1, null, { hold: 1 }],
        ['neutral', 'panzer_hummel', 15, 1, 1, null, { hold: 1 }],
        ['neutral', 'alexander_drone', 8, 6, 1, null, { hold: 1 }],
        ['neutral', 'alexander_drone', 15, 6, 1, null, { hold: 1 }],
        ['neutral', 'alexander_drone', 7, 7, 1, null, { hold: 1 }],
        ['neutral', 'gardmare', 9, 2, 1],
        ['neutral', 'gardmare', 16, 3, 1],
        ['neutral', 'estrella', 13, 7, 1, null, { skipNormal: true }],
        ['neutral', 'alexander_drone', 6, 4, 1, null, { skipNormal: true }],
      ],
      objective: 'Destroy Smilas’s unit and end the coup.',
      win: { kill: ['smilas'] },
      lose: { turns: 12 },
      stars: [{ capture: ['Élysée Palace'] }, { losses: 2 }],
      victory: 'Smilas dies with his coup. The E.U. survives, split in two, and the Wyvern Squad finally goes home.',
      events: [
        {
          turn: 1,
          say: [
            ['Jan@eu', 'Smilas wants to crown himself Emperor of Europe. We hold until the captain gets here.'],
            ['smilas', 'A capable dictator serves mankind better than a democracy of fools. Paris is mine.'],
          ],
        },
        {
          turn: 3,
          say: [['ashley', 'Miss me? Asura Strike Force, follow my lead!']],
          spawn: [['eu', 'alexander_elite', 5, 9, 1, 'ashley']],
        },
      ],
    },
  ];

