#!/usr/bin/env python3
"""Regenerate the global GSHHG intermediate-resolution coastline atlas.

All coasts use the same 0.025-degree simplification. Requires Basemap and
Shapely at generation time; runtime uses only the generated static JS.
No game engine, tile, ownership or terrain data is changed.
"""
from pathlib import Path
import json
from shapely.geometry import Polygon
from mpl_toolkits.basemap import Basemap

ROOT = Path(__file__).resolve().parents[1]
map_data = ROOT / "dist/ui/geography-data.js"
m = Basemap(projection="cyl", llcrnrlon=-180, llcrnrlat=-54,
            urcrnrlon=180, urcrnrlat=74, resolution="i")

def rings(polygons, tolerance=0.025):
    output = []
    for obj in polygons:
        coords = Polygon(obj.get_coords()).simplify(
            tolerance, preserve_topology=True).exterior.coords
        points = [[round(float(x), 4), round(float(y), 4)]
                  for x, y in coords]
        if len(points) > 3:
            output.append(points)
    return output

previous = map_data.read_text()
# Carry the hand-drawn biome shapes over: decode the JSON array that follows "biomes":
# (whatever key, if any, comes after it), so the script can run again on its own output.
start = previous.find('"biomes":')
if start < 0:
    raise RuntimeError("Expected previous biome shapes in geography data")
biomes, _ = json.JSONDecoder().raw_decode(previous, start + len('"biomes":'))
data = {"land": rings(m.landpolygons), "water": rings(m.lakepolygons),
        "biomes": biomes}
prefix = (
    "/* Global GSHHG intermediate-resolution geography (public domain), "
    "generated by tools/export_geography.py.\n"
    " * One coastline source everywhere; no differently coloured regional "
    "patches or changed gameplay tiles. */\n"
    "'use strict';\nconst GEOGRAPHY_SHAPES = "
)
map_data.write_text(prefix + json.dumps(data, separators=(",", ":")) + ";\n")
print("Global land", len(data["land"]), "polygons")
print("Inland water", len(data["water"]), "polygons")
print("Atlas", map_data.stat().st_size, "bytes")
