#!/usr/bin/env python3
"""Publish finished local art, never raw downloads, into the GitHub Pages payload.

Run after local_art_prepare.py: python3 tools/publish_art.py
The input defaults to dist/local-art; --source accepts another processed art folder.
Requires Pillow (also required by the preparation tool). Commit dist/assets/art afterwards.
"""
import argparse
import hashlib
import json
from pathlib import Path
import shutil
import sys

from PIL import Image
import local_art_manifest

ROOT = Path(__file__).resolve().parents[1]
PUBLIC = ROOT / 'dist/assets/art'
PREFIX = '// Generated by tools/publish_art.py; edit manifest.json through the publisher.\n'


def publish(source, output=PUBLIC):
    source = Path(source).resolve()
    output = Path(output).resolve()
    known = local_art_manifest.known_ids(ROOT / 'dist')
    manifest_path = source / 'manifest.json'
    if not manifest_path.is_file():
        raise ValueError(f'No processed manifest at {manifest_path}. Run local_art_prepare.py first.')
    manifest = json.loads(manifest_path.read_text())
    # Merge into the published manifest: a local folder holding only some finished images updates
    # those entries and keeps every other published one (validate_assets.cjs requires full coverage).
    public_path = output / 'manifest.json'
    previous = json.loads(public_path.read_text()) if public_path.is_file() else {}
    result = {'base': 'assets/art/', **{kind: {k: v for k, v in previous.get(kind, {}).items() if k in known[kind]}
                                       for kind in known}}
    copies = []
    for kind in known:
        for key, value in sorted(manifest.get(kind, {}).items()):
            if key not in known[kind]:
                raise ValueError(f'Unknown {kind} id: {key}')
            entry = {'src': value} if isinstance(value, str) else value.copy()
            relative = Path(entry['src'])
            if len(relative.parts) != 2 or relative.parts[0] != kind:
                raise ValueError(f'Only processed {kind}/ files may be published: {relative}')
            path = (source / relative).resolve()
            if source not in path.parents or not path.is_file():
                raise ValueError(f'Missing or unsafe image: {relative}')
            with Image.open(path) as image:
                image.verify()
            # Header/CRC verification alone can miss a truncated compressed image stream.
            with Image.open(path) as image:
                image.load()
            suffix = path.suffix.lower()
            if suffix not in ('.png', '.jpg', '.jpeg', '.webp', '.gif'):
                raise ValueError(f'Unsupported processed image: {relative}')
            digest = hashlib.sha256(path.read_bytes()).hexdigest()[:12]
            target = f'{kind}/{key}-{digest}{suffix}'
            clean = {'src': target}
            for axis in ('fx', 'fy'):
                if axis in entry:
                    value = entry[axis]
                    if isinstance(value, bool) or not isinstance(value, (int, float)) or not 0 <= value <= 1:
                        raise ValueError(f'Invalid {axis} focus for {key}')
                    clean[axis] = value
            result[kind][key] = clean
            copies.append((path, output / target))
    if not copies:
        raise ValueError('No finished images found. Existing public art has not been changed.')
    # Validate the entire source before writing anything to the public folder.
    for source_file, target in copies:
        target.parent.mkdir(parents=True, exist_ok=True)
        shutil.copyfile(source_file, target)
    # Remove published images that a new version replaced and nothing references any more.
    referenced = {entry['src'] for kind in known for entry in result[kind].values()}
    for kind in known:
        for entry in previous.get(kind, {}).values():
            old = (output / entry.get('src', '')).resolve()
            if entry.get('src') not in referenced and output in old.parents and old.is_file():
                old.unlink()
    payload = json.dumps(result, indent=2, ensure_ascii=True)
    (output / 'manifest.json').write_text(payload + '\n')
    (output / 'manifest.js').write_text(PREFIX + 'globalThis.KnightmareArtManifest = ' + payload + ';\n')
    for kind in known:
        print(f'{kind}: published {len(result[kind])}/{len(known[kind])}')
        print('  drawn fallbacks:', ', '.join(k for k in known[kind] if k not in result[kind]) or 'none')
    print('Published finished art only. Commit dist/assets/art/ to deploy it.')
    return result


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--source', type=Path, default=ROOT / 'dist/local-art')
    args = parser.parse_args()
    try:
        publish(args.source)
    except (OSError, ValueError, KeyError, TypeError) as error:
        print(f'Art publication failed: {error}', file=sys.stderr)
        return 1
    return 0


if __name__ == '__main__':
    sys.exit(main())
